### PR TITLE
Add buttons on left/right of the stack to open search and drop card into a neighbor stack

### PR DESCRIPTION
**Pull request by jurgenwerk**
Ticket: [CS-5444](https://linear.app/cardstack/issue/CS-5444/on-click-of-place-card-button-to-left-or-right-of-center-stack-slide)

This PR adds a feature where a user can click on the left or right button, which opens the search panel and then when a card gets clicked in the search component (currently one can only click on a recent card because the search isn't implemented yet), it will be placed to the left or right stack.

https://www.loom.com/share/ed5ce9ab6fdc488ab8a599ad46abef11?sid=e3f3575d-7476-4490-8476-e014c5acfd39

### CODE REVIEW

**Comment by jurgenwerk** [comment]
I just realized it would probably be more suitable to use the "Go" action rather than making the click on the recent card to open the card on the stack directly. Let me know what you think

**Review by burieberry — APPROVED** [review]
It would look nicer if we allowed each stack's width to be wider when there're 2 stacks side by side

**Comment by jurgenwerk** [comment]
@burieberry you're right - will add an adjustment to make them a bit wider.

**Comment by jurgenwerk** [comment]
Made the stacks wider: image

**Review by habdelra — APPROVED** [review]

**Review by FadhlanR — APPROVED** [review]

**Pull request merged**
