### PR TITLE
Auto save for card editor in code mode

### PR DESCRIPTION
**Pull request by habdelra**
Auto save for the card editor panel in code mode

card-editor-auto-save

### CODE REVIEW

**Review by backspace — APPROVED** [review]
I tried it out, looks good, I’d expect a progress indicator or some thing showing that autosaving is happening (on both sides) but maybe that’s a separate issue?

**Review by lukemelia — APPROVED** [review]
LGTM. I thought it was possible to accomplish what you want to do with a resource, by hanging onto the previous returned result and returning the same object when appropriate.

**Comment by habdelra** [comment]
> LGTM. I thought it was possible to accomplish what you want to do with a resource, by hanging onto the previous returned result and returning the same object when appropriate.

yeah i tried many different variations of that, none of them worked, it all stemmed not from the card resource--but the file resource that the card resource consumes changing (because of a received SSE event). no state that I can hold on to in the card resource can prevent that from triggering a new load.

**Comment by habdelra** [comment]
> I tried it out, looks good, I’d expect a progress indicator or some thing showing that autosaving is happening (on both sides) but maybe that’s a separate issue?

yup--that is the next ticket i'm working on

**Pull request merged**
