### PR TITLE
tools: Move VS Code extension into monorepo

### PR DESCRIPTION
**Pull request by backspace**
This preserves the history of [`boxel-vscode-extension`](https://github.com/cardstack/boxel-vscode-extension) apart from 6bfe48d, which was added [after I forked](https://github.com/cardstack/boxel-vscode-extension/commit/1c91382da2c9714728d87c7a332aa282a801be12).

There’s a CI job but it only builds and packages the code, followup PRs will add versioning, publishing, linting, and other integration.

7c9509a has some questionable type fixes, also to be addressed in followups if needed.

### CODE REVIEW

**Comment by IanCal** [comment]
IMO the key thing with moving to the monorepo is being able to import from the rest of the code

auth.ts should be removed and instead we should import https://github.com/cardstack/boxel/blob/main/packages/runtime-common/realm-auth-client.ts - it's the same file (although I've inlined two small imports).

https://github.com/cardstack/boxel/pull/1606/files#diff-c8b43f9a423d927099533570f95adf544cd3cc5968b2dac511150df0d6234f6a

**Comment by backspace** [comment]
> IMO the key thing with moving to the monorepo is being able to import from the rest of the code

ya I got started on that in 8ce2e0c, just a beginning to expose the errors that helped me figure out what `tsconfig.json` changes might be needed, now I’ll get rid of the rest of the file and hopefully no more errors will happen 🤞🏻

**Comment by backspace** [comment]
Thanks for the review on #1614, @IanCal, can you check this one out too? That builds on this, I kept them separate for ease of reviewing.

**Comment by habdelra** [comment]
Can we add a lint to this workspace as well? (kicked off from `ci-lint.yaml`)

**Comment by habdelra** [comment]
> Can we add a lint to this workspace as well? (kicked off from `ci-lint.yaml`)

oh wait, nvm, I see that is actually part of https://github.com/cardstack/boxel/pull/1630

**Review by habdelra — APPROVED** [review]

**Pull request merged**
