### PR TITLE
ui: Merge SearchInput and ValidationState into BoxelInput

### PR DESCRIPTION
**Pull request by backspace**
This removes `boxel-ui`’s `Input::SearchInput` and `Input::ValidationState`, combining their features into `Input`, as this is something I need in #790.

Boxel Components 2023-11-10 14-03-49

The existing controls had confusing overlap and some weird incompatibilities like here with `@hasValidation` on `SearchInput`:

Image 2023-11-10 14-20-12

Alignment problems, before and after:

<table>
<tbody>
<tr>
<td>

Image 2023-11-10 15-06-30

</td>
<td>

Image 2023-11-10 15-05-31

</td>
</tr>
</tbody>
</table>

This has some known issues but they already existed in `InputValidationState`, they were masked by the Freestyle page not exposing a `@type` control:

<table>
<tbody>
<tr>
<td>

Image 2023-11-10 15-03-15

</td>
</tr>
<tr>
<td>

Image 2023-11-10 15-01-46

</td>
</tr>
</table>

I’m declaring this out of scope since it was already a problem and we don’t currently have anything producing these outcomes.

### CODE REVIEW

**Comment by backspace** [comment]
Making note of this here though I haven’t yet added in `ValidationState` things so it might be superseded

Boxel Components 2023-11-07 12-39-11

**Review by jurgenwerk — APPROVED** [review]
Pretty cool, thanks for consolidating this and for taking care of the alignments!

I tested it on search inputs and the edit field input and it works ok. 

There is one small thing I found - when hovering over X the mouse cursor should be `pointer` so it's clear it's clickable

image

**Review by burieberry — APPROVED** [review]
This is great!

**Comment by backspace** [comment]
hmm how strange, I didn’t even see that while working on this! Thanks for pointing it out. But it turns out to be because the old `SearchInput` didn’t use `type="search"`, that control is added by the user agent, here’s Safari:

Personal —  input type= search  - HTML: HyperText Markup Language | MDN 2023-11-13 10-37-13

vs Chrome:

input type= search  - HTML: HyperText Markup Language | MDN 2023-11-13 10-35-35

Firefox doesn’t show it by default, it’s [feature flagged](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features#layout_for_input_typesearch)!

So I guess it’s out of my hands really. I do wonder whether the magnifying glass icon should go away when content has been entered as two icons beside each other seems a bit weird, I feel like this is a pattern I‘ve seen but now I can’t find it… I’m going to make this a design question.

**Pull request merged**
