### PR TITLE
Display default file-tree even if url is not found

### PR DESCRIPTION
**Pull request by burieberry**
Continue displaying file tree if url is not found and related clean-up

incorrect-url

### CODE REVIEW

**Review by backspace — APPROVED** [review]
This happens to fix the same thing as I was addressing in #643 😯 your implementation has some improvements though so I can just reduce that to the test

**Comment by burieberry** [comment]
> This happens to fix the same thing as I was addressing in #643 😯 your implementation has some improvements though so I can just reduce that to the test

Ah didn't realize there was another ticket. Looks like it's the same solution. If yours is ready to go, merge it and I can pull those changes into my PR

**Comment by backspace** [comment]
yours seems more thorough though! Mine still has two `FileTree` depending on conditionals.

**Comment by burieberry** [comment]
> yours seems more thorough though! Mine still has two `FileTree` depending on conditionals.

Ok then, I'll merge. Thanks!

**Pull request merged**
