### PR TITLE
Fix discontinuity on LHS upon editing file

### PR DESCRIPTION
**Pull request by tintinthong**
Use resource to react to file
Use service to expose declarations to consumers 
I still dont know what does this do to the lifecycle of resource -- like how do i destroy them properly
shud use this as an opportunity to unify the shared moduleSyntax

right now only for lhs

https://github.com/cardstack/boxel/assets/8165111/f1c45a47-1135-486a-b02b-bbd4c0e4abe7

https://github.com/cardstack/boxel/assets/8165111/936f6b9a-ecaf-4949-8ac0-63752fdb7c8b

### CODE REVIEW

**Comment by tintinthong** [comment]
@habdelra this is still wip. I have gotten much better control over the blinking (at least for the lhs ) by using a solution like this where I put a service in front of consumers of `declarations`.  

Do you have thoughts about this implementation based upon what new tooling is available for the new card resources? 

I havent used anything from the refactor bcos I was not sure how to consolidate with the modules rather than card instance

**Comment by habdelra** [comment]
> @habdelra this is still wip. I have gotten much better control over the blinking (at least for the lhs ) by using a solution like this where I put a service in front of consumers of `declarations`.
> 
> Do you have thoughts about this implementation based upon what new tooling is available for the new card resources?
> 
> I havent used anything from the refactor bcos I was not sure how to consolidate with the modules rather than card instance

this doesn't seem super sustainable--basically it means that you can only ever have a single list of declarations in the app at a time because services are singletons. if we have another consumer of declarations outside of the left hand panel this approach will no longer work. resources are much more dynamic in these regards. Moreover, if we have mulitple loaders governing different parts of the app (which i think we will soon), i think this will also break down since the service can only use a single loader at a time--so which loader would you use? Every consumer of declarations would need its own unique service...

 To consume the new work, any place where you were previously consuming a `CardDef` you'd consume a `CardResource` instead and use the `CardResource.card` to get the card out of it. For your stuff you might actually have to operate at a level above cards--specifically modules. I think you'd need a similar approach to what I did for `CardResources`, where you would have a `ModuleResource` that takes as input a `url: () => URL, loader: () => Loader`. Inside of it, it would have a tracked property called `module`. And any component that currently takes in a module as an argument would take in a `MofuleREsource` instead, and use the `ModuleResource.module` to get access to a module. This way the loader can change, but the `ModuleResource` instance will stay constant (it will just spit out a different module internally). so any components that depend on a ModuleResource will not be invalidated when the loader changes because the ModuleResource stays contant while the loader changes within the ModuleResource's thunk.

**Comment by tintinthong** [comment]
@habdelra thanks for the feedback

> this doesn't seem super sustainable--basically it means that you can only ever have a single list of declarations in the app at a time because services are singletons. if we have another consumer of declarations outside of the left hand panel this approach will no longer work. resources are much more dynamic in these regards. Moreover, if we have mulitple loaders governing different parts of the app (which i think we will soon), i think this will also break down since the service can only use a single loader at a time--so which loader would you use? Every consumer of declarations would need its own unique service...

Ok yea. I thought this was awkward too because I cudn tie destruction of my resources to any component. I think the question of which loader is kinda a tough one to entangle if our loader is still a service. I think the different areas of the app syncing after a flush still depends on the resources defaulting to the loader service loader. But I understand the concern, I can try my best to derive the loader from the card or card definition. 

> where you would have a ModuleResource that takes as input a url: () => URL, loader: () => Loader. Inside of it, it would have a tracked property called module. And any component that currently takes in a module as an argument would take in a MofuleResource instead, and use the ModuleResource.module to get access to a module. This way the loader can change, but the ModuleResource instance will stay constant (it will just spit out a different module internally). so any components

This is exactly how the import resource already worked

I have implemented this https://github.com/cardstack/boxel/pull/805.

**Comment by habdelra** [comment]
> @habdelra thanks for the feedback
> 
> > this doesn't seem super sustainable--basically it means that you can only ever have a single list of declarations in the app at a time because services are singletons. if we have another consumer of declarations outside of the left hand panel this approach will no longer work. resources are much more dynamic in these regards. Moreover, if we have mulitple loaders governing different parts of the app (which i think we will soon), i think this will also break down since the service can only use a single loader at a time--so which loader would you use? Every consumer of declarations would need its own unique service...
> 
> Ok yea. I thought this was awkward too because I cudn tie destruction of my resources to any component. I think the question of which loader is kinda a tough one to entangle if our loader is still a service. I think the different areas of the app syncing after a flush still depends on the resources defaulting to the loader service loader. But I understand the concern, I can try my best to derive the loader from the card or card definition.
> 
> > where you would have a ModuleResource that takes as input a url: () => URL, loader: () => Loader. Inside of it, it would have a tracked property called module. And any component that currently takes in a module as an argument would take in a MofuleResource instead, and use the ModuleResource.module to get access to a module. This way the loader can change, but the ModuleResource instance will stay constant (it will just spit out a different module internally). so any components
> 
> This is exactly how the import resource already worked
> 
> I have implemented this #805.

yeah, i mentioned it in the sprint review yesterday, but i think the loader service is gonna have to die. that's why i made all the utilities for deriving a loader and api from a running card. that way you can use any loader to create the card, and then when you need to work more with the card you can derive the correct loader or API to use for interacting with the card. The loader service was originally created back in the code route days to give us an easy way to update teh loader when a module changed. it does that, but the downside is that it invalidates every card in the app's memory which makes it hard to do stateful things with card instances because the card instances may be incompatible with eachother from state to state. probably its time for us to evolve past the "single loader" strategy....

cool regarding #805, i'll review that today

**Comment by tintinthong** [comment]
> > @habdelra thanks for the feedback
> > > this doesn't seem super sustainable--basically it means that you can only ever have a single list of declarations in the app at a time because services are singletons. if we have another consumer of declarations outside of the left hand panel this approach will no longer work. resources are much more dynamic in these regards. Moreover, if we have mulitple loaders governing different parts of the app (which i think we will soon), i think this will also break down since the service can only use a single loader at a time--so which loader would you use? Every consumer of declarations would need its own unique service...
> > 
> > 
> > Ok yea. I thought this was awkward too because I cudn tie destruction of my resources to any component. I think the question of which loader is kinda a tough one to entangle if our loader is still a service. I think the different areas of the app syncing after a flush still depends on the resources defaulting to the loader service loader. But I understand the concern, I can try my best to derive the loader from the card or card definition.
> > > where you would have a ModuleResource that takes as input a url: () => URL, loader: () => Loader. Inside of it, it would have a tracked property called module. And any component that currently takes in a module as an argument would take in a MofuleResource instead, and use the ModuleResource.module to get access to a module. This way the loader can change, but the ModuleResource instance will stay constant (it will just spit out a different module internally). so any components
> > 
> > 
> > This is exactly how the import resource already worked
> > I have implemented this #805.
> 
> yeah, i mentioned it in the sprint review yesterday, but i think the loader service is gonna have to die. that's why i made all the utilities for deriving a loader and api from a running card. that way you can use any loader to create the card, and then when you need to work more with the card you can derive the correct loader or API to use for interacting with the card. The loader service was originally created back in the code route days to give us an easy way to update teh loader when a module changed. it does that, but the downside is that it invalidates every card in the app's memory which makes it hard to do stateful things with card instances because the card instances may be incompatible with eachother from state to state. probably its time for us to evolve past the "single loader" strategy....
> 
> cool regarding #805, i'll review that today

thx. Makes sense. Perhaps 1st step we can do for the loader stuff is to stop defaulting to the loader service and force a loader to be passed down

**Pull request closed without merging**
