### PR TITLE
Handle plan changes in stripe customer portal

### PR DESCRIPTION
**Pull request by jurgenwerk**
This adds a new case in the `invoice.payment_succeeded` Stripe webhook handler where the billing reason is `subscription_update`.

This webhook is sent when a user changes a subscription in the customer portal (fore example from Free to Creator plan).

When there is a plan upgrade, the implementation will end the subscription and start a new one where it will give the user  a prorated credit allowance. Proration happens when the user switches plans in the middle of the billing cycle. In this case, Stripe will immediately credit the user in money for time left on the old plan, and charge for the remaining time on the new plan. We convert this to credits and give the user prorated credits for the new subscription.

When there is a plan downgrade, nothing special happens, the user will be given the new plan's worth of credit allowance (and expire the old allowance in case there is any left). We can have this simplicity because we have an option enabled in Stripe that assures that when a user changes the plan to a smaller one, the change will be applied at the end of the billing period.

### CODE REVIEW

**Review by backspace — APPROVED** [review]
approval pending correct merge

this is orthogonal to the PR but your comment “we have an option enabled in Stripe” made me wonder whether we should be [managing Stripe in Terraform](https://registry.terraform.io/providers/lukasaron/stripe/latest/docs), maybe overkill but it would let the secrets in AWS be directly dependent at least

**Comment by jurgenwerk** [comment]
@backspace that's interesting, we can discuss in our next boxel meeting if we want to plan setting up Stripe using Terraform.

**Review by FadhlanR — APPROVED** [review]

**Review by lukemelia — APPROVED** [review]
Looks good. Do you think it would be possible/useful to factor out database queries from the proration math? This would let us have a module responsible for the proration calculation that is a pure function and can have various edge cases unit tested quickly.

**Comment by jurgenwerk** [comment]
@lukemelia good suggestion, I extracted the proration logic in https://github.com/cardstack/boxel/pull/1776/commits/e431fad61164a0a07bebfe4f309368b8d945680a

**Pull request merged**
