### PR TITLE
Update matrix email templates

### PR DESCRIPTION
**Pull request by FadhlanR**
~~We need to include a link in the email verification for password reset because the button is not working.~~(EDIT)

After I discussed with @jurgenwerk , I decided to change the purpose of this PR. This PR is purposed to make matrix email templates be more compatible with email clients. So, I updated header style into inline styles, used `a` instead of `button`, and used `table` instead of `flexbox`. Here's the screenshot of the HTML email in SMTP4dev and gmail.

SMTP4dev:
Screen Shot 2024-01-11 at 16 54 47

gmail:

https://github.com/cardstack/boxel/assets/12637010/7421d27f-29fb-4653-b9af-a1ac3d5c39bb

Styles and button are working now in gmail.

### CODE REVIEW

**Comment by jurgenwerk** [comment]
I'm confused - what do you mean by the button is not working? And why keep it if it's not working?

**Comment by FadhlanR** [comment]
> I'm confused - what do you mean by the button is not working? And why keep it if it's not working?

The button is working in SMTP4dev email, but it's not functioning in Gmail.

**Comment by jurgenwerk** [comment]
image

This is how the email looks in gmail. The button is not working because the onclick handler is stripped out. If you want to keep the button then maybe try an anchor tag instead and design it as a button? But in any case–if a button is not working it's not a good user experience to have it. 

Other remarks:
1. The "
Boxel
Reset password requested" doesn't look good. Consider wrapping these into heading tags? Is this because the css is not being applied?

2. It says "use the link below" but there's a button down there, would be good to say "click the button" to be consistent

**Comment by lukemelia** [comment]
The rules for building HTML/CSS that looks good in email clients is quite different from the usual rules. Here's a primer: https://www.smashingmagazine.com/2017/01/introduction-building-sending-html-email-for-web-developers/

**Comment by jurgenwerk** [comment]
Thanks for making these changes, unfortunately production email templating is still in dark ages. Possible to paste screenshots of all these templates when rendered in gmail?

**Comment by FadhlanR** [comment]
> Thanks for making these changes, unfortunately production email templating is still in dark ages. Possible to paste screenshots of all these templates when rendered in gmail?

@jurgenwerk We currently have 3 scenarios that need email verification. Here are the screenshot of those emails in gmail.

- Email verification to register.

https://github.com/cardstack/boxel/assets/12637010/cbe1c919-4b65-4e88-8153-a0ad9b0d07fa

- Email verification for change email address.

https://github.com/cardstack/boxel/assets/12637010/9d73208b-171c-437e-8d6f-dca641e35ad3

- Email verification to reset password.

https://github.com/cardstack/boxel/assets/12637010/7421d27f-29fb-4653-b9af-a1ac3d5c39bb

**Comment by jurgenwerk** [comment]
1. Is it needed to have both the button and the link and have both go to the same place? I suppose it's good to have redundancy in case the button doesn't show up but with this fix I don't see why it would not show up. Just a minor comment, I'm ok if you want to keep both. 

2. "Your email has been validated" - This text lacks information on what to do next. Should the user close the window, go back to the app,...?

**Comment by FadhlanR** [comment]
> 1. Is it needed to have both the button and the link and have both go to the same place? I suppose it's good to have redundancy in case the button doesn't show up but with this fix I don't see why it would not show up. Just a minor comment, I'm ok if you want to keep both.
> 2. "Your email has been validated" - This text lacks information on what to do next. Should the user close the window, go back to the app,...?

1. I think we can keep both for now to make it consistent with the design.
2. Updated, here's the screenshot.

https://github.com/cardstack/boxel/assets/12637010/a32ad751-75c3-4ae8-8327-74de01cf596f

**Review by jurgenwerk — APPROVED** [review]

**Pull request merged**
