### PR TITLE
ui: Add listing of all icons in Freestyle

### PR DESCRIPTION
**Pull request by backspace**
You can see a preview [here](https://uiicons-cs-6700.boxel-ui-preview.stack.cards/?f=All%20Icons&s=Components&ss=%3CIconButton%3E).

screencast 2024-04-11 11-04-34

### CODE REVIEW

**Review by jurgenwerk — APPROVED** [review]
Really nice!

**Review by burieberry — APPROVED** [review]
This is great. Makes it clear to see how some icons are overflowing their containers or have strange/uneven paddings.

**Comment by lukemelia** [comment]
Love it. I think adding a "Show viewbox" toggle would be great.

**Comment by backspace** [comment]
Thanks all, I’ve added that and a checkbox to hide overflow which highlights the problems @burieberry pointed out:

screencast 2024-04-11 11-04-34

**Comment by backspace** [comment]
Actually I failed to consider one of the basic things about the box model: the width includes borders by default, so I need to use `calc` to add to the width when the border exists, with that none of the icons are truncated:

Boxel Components 2024-04-11 14-24-11

**Pull request merged**
