### PR TITLE
tools: Fix accept headers and response-parsing

### PR DESCRIPTION
**Pull request by backspace**
This is currently extending #1670, which is awaiting review.

With this change, here’s an enumeration of current API and Boxel Tools extension realm filesystem capabilities:

<table>
<tr>
<th></th>
<th colspan=2>read</th>
<th colspan=2>create</th>
<th colspan=2>update</th>
<th colspan=2>rename</th>
<th colspan=2>delete</th>
</tr>
<tr>
<th></th>
<th>API</th><th>Extension</th>
<th>API</th><th>Ext</th>
<th>API</th><th>Ext</th>
<th>API</th><th>Ext</th>
<th>API</th><th>Ext</th>
</tr>
<tr>
<th>text file</th>
<td>☑️</td><td>☑️</td>
<td>☑️</td><td>☑️</td>
<td>☑️</td><td>☑️</td>
<td>☑️<sup>1</sup></td><td>✖️</td>
<td>☑️</td><td>✖️</td>
</tr>
<tr>
<th>binary file</th>
<td>☑️</td><td>✖️</td>
<td>✖️<sup>2</sup></td><td>✖️</td>
<td>✖️<sup>2</sup></td><td>✖️</td>
<td>✖️</td><td>✖️</td>
<td>☑️</td><td>✖️</td>
</tr>
<tr>
<th>directory</th>
<td>☑️</td><td>☑️</td>
<td>✖️<td>✖️</td>
<td>✖️</td><td>✖️</td>
<td>✖️</td><td>✖️</td>
<td>✖️</td><td>✖️</td>
</tr>
</table>

<sup>1</sup>: not directly supported but can be accomplished with delete and create
<sup>2</sup>: appears to work but created/updated file is not readable

### CODE REVIEW

**Comment by habdelra** [comment]
do we want to include cut/copy/paste in that grid?

**Comment by habdelra** [comment]
for directories, I think when you make a new file we'll automatically populate any interior directories that don't yet exist. so in that way we are kind of like git in that directories only exist when they contain files

**Comment by habdelra** [comment]
binary files are probably using the wrong headers--probably we need to be using Octet-Stream.... but also probably we tackle this until we have bake in proper binary support into the realm API...

**Review by habdelra — APPROVED** [review]

**Comment by backspace** [comment]
> do we want to include cut/copy/paste in that grid?

I can add that, I’ve never used that and forgot it existed 😆

> for directories, I think when you make a new file we'll automatically populate any interior directories that don't yet exist. so in that way we are kind of like git in that directories only exist when they contain files

ah I didn’t realise that, I tried it with the extension and it failed but it succeeded with the API, so… 😬

> binary files are probably using the wrong headers--probably we need to be using Octet-Stream.... but also probably we tackle this until we have bake in proper binary support into the realm API...

ya trying to support binary seems like a can of worms

**Pull request merged**
