### PR TITLE
Introduce start:development command which starts dev environment with option to go /base or /demo

### PR DESCRIPTION
**Pull request by jurgenwerk**
This PR addresses the desire to run development with the same setup we have on staging and production. Should be easier to test and debug locally this way. 

The new command is: `pnpm start:development`

It will start the realm server in a way where you can visit http://localhost:4201/ and get an option to visit either /base or /demo realm:

image

Thanks @habdelra for help on this one!

### CODE REVIEW

**Comment by jurgenwerk** [comment]
I just discovered 2 problems:

1. `pnpm start:development` in /realm-server doesn't work without `pnpm start` in /host
 - addressed in https://github.com/cardstack/boxel/pull/428/commits/d1826d779bf021b9a6e3270f086af9afe6298ec4 by removing the option, not sure if this is correct but the app seems to work normally ✅
2. tests fail because it's timing out: 
> Timed out waiting for: http-get://localhost:4201/base/fields/boolean-field?acceptHeader=application%2Fvnd.card%2Bjson, http-get://localhost:4202/test/hassan?acceptHeader=application%2Fvnd.card%2Bjson

- not sure yet, investigating...
- edit: looks like this was resolved by the fix above! ✅

**Comment by lukemelia** [comment]
Do we need README updates to go along with this?

**Comment by jurgenwerk** [comment]
@lukemelia yes! Thanks for reminding me. Will adjust it

**Review by habdelra — APPROVED** [review]

**Review by habdelra — APPROVED** [review]

**Review by tintinthong — APPROVED** [review]
LGTM thanks! Only Update readme that luke talked about

**Pull request merged**
