### PR TITLE
Passing more context to setTitle + get apply action to set a title 

### PR DESCRIPTION
**Pull request by tintinthong**
The point of this PR is to 
- pass patch card context to `setTitle` gpt
- to trigger `setTitle` via clicking of the "Apply" rather than waiting for roundtrip event to trigger it

A way to test this is to have a list of commands sent and the last one you "apply" is the one which names the room

### CODE REVIEW

**Comment by tintinthong** [comment]
I'm not sure if this is a result of this PR https://cardstack.sentry.io/issues/5348088638/?environment=development&project=4506860646170624&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=1

**Comment by IanCal** [comment]
I think moving the initalRoomSync so high means that we'll be running that a huge number of times on historical messages

**Comment by IanCal** [comment]
Two thoughts, one is that we don't need to wait for a user to click apply, we know we've sent one so we could use that. That saves trying to get the full room on every apply.

It may also be good to include the attached cards in the data sent.

**Comment by tintinthong** [comment]
@IanCal 

> I think moving the initalRoomSync so high means that we'll be running that a huge number of times on historical messages

Ahh good point

> Two thoughts, one is that we don't need to wait for a user to click apply, we know we've sent one so we could use that. That saves trying to get the full room on every apply.

I recall thru our discussion we'd want to capture the response from a function call. To me it made sense that we didn't just look for the args that was sent back by open ai but the command that the user agrees on. Is it worth while capturing another client listener to look out for reaction events? That way we can move the history down as before and call it sparingly in our new listener

> It may also be good to include the attached cards in the data sent.

Yeap yeap. Overlooked this

**Comment by IanCal** [comment]
> > Two thoughts, one is that we don't need to wait for a user to click apply, we know we've sent one so we could use that. That saves trying to get the full room on every apply.
> 
> I recall thru our discussion we'd want to capture the response from a function call. To me it made sense that we didn't just look for the args that was sent back by open ai but the command that the user agrees on. Is it worth while capturing another client listener to look out for reaction events? That way we can move the history down as before and call it sparingly in our new listener
> 

Yeah that could make sense, I've not really explored what you can register. Sounds good.

I was thinking about performance but tbh we should probably add some LRU cache of recently accessed room histories (not in scope here) as that would solve both what I'm thinking about here and lessen the load on the matrix server for all other comments too.

**Comment by tintinthong** [comment]
Screenshot 2024-05-16 at 12 37 41


User message to chat titling system

```
Applying patchCard with the payload {"type":"patch","id":"http://localhost:4201/drafts/Author/1","patch":{"attributes":{"firstName":"Justin"}},"eventId":"$3GuObu_9xs2N1GVJpTD8Cy5cIsioJXUBzbmGD5X7H7c"}. The patch being made is applied to the following Full card data: {"type":"card","id":"http://localhost:4201/drafts/Author/1","attributes":{"firstName":"Alice","lastName":"Enwunder","photo":null,"body":"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.","description":null,"thumbnailURL":null},"meta":{"adoptsFrom":{"module":"../author","name":"Author"}}}
```

**Comment by tintinthong** [comment]
Screenshot 2024-05-16 at 12 46 17

```
Applying patchCard with the payload {"type":"patch","id":"http://localhost:4201/drafts/BlogPost/1","patch":{"attributes":{},"relationships":{"authorBio":{"links":{"self":null}}}},"eventId":"$3dtQs1llW6E-d57uozELvt735xSTeZ_sCNEcso_EF4E"}. The patch being made is applied to the following Full card data: {"type":"card","id":"http://localhost:4201/drafts/BlogPost/1","attributes":{"title":"Mad As a Hatter","slug":"mad-as-a-hatter","body":"## Where it all begins\\n\\nThis is a story of a man named [Brady](https://eightiesforbrady.com), who was bringing up three very lovely girls under the rule of the Queen of Hearts.","description":null,"thumbnailURL":null},"relationships":{"authorBio":{"links":{"self":"../Author/1"},"data":{"type":"card","id":"http://localhost:4201/drafts/Author/1"}}},"meta":{"adoptsFrom":{"module":"../blog-post","name":"BlogPost"}}}
```

**Comment by tintinthong** [comment]
> > > Two thoughts, one is that we don't need to wait for a user to click apply, we know we've sent one so we could use that. That saves trying to get the full room on every apply.
> > 
> > 
> > I recall thru our discussion we'd want to capture the response from a function call. To me it made sense that we didn't just look for the args that was sent back by open ai but the command that the user agrees on. Is it worth while capturing another client listener to look out for reaction events? That way we can move the history down as before and call it sparingly in our new listener
> 
> Yeah that could make sense, I've not really explored what you can register. Sounds good.
> 
> I was thinking about performance but tbh we should probably add some LRU cache of recently accessed room histories (not in scope here) as that would solve both what I'm thinking about here and lessen the load on the matrix server for all other comments too.

Looks like we can separate the listeners if we want to perform different handles. Just call `client.on(Room.Timeline`. Listeners run in the order they're defined. I think this is the preferred pattern. We don't need to put everything into a single Room.Timeline. 

I think theres an opportunity to listen to the syncing event too which would be ideal in another PR

**Review by IanCal — APPROVED** [review]
I think there's a merge conflict but otherwise lgtm

**Pull request merged**
