### PR TITLE
Convert realm-server node tests to a single process

### PR DESCRIPTION
**Pull request by FadhlanR**

### CODE REVIEW

**Review by lukemelia — CHANGES_REQUESTED** [review]
As we discussed, the intention for this task is to update realm-server node tests to use TestRealm so that running the realm server as a separate process is not needed to successfully run tests.

**Comment by FadhlanR** [comment]
@lukemelia Do you mean the same `TestRealm` that we used in the host's tests? If yes, How would we deal with the indexing process? Because in the host's tests, we mock the local indexer and trigger the indexing process by rendering the `CardPrerender` component. I'm not sure how to do that in the realm server. Do we need to install ember in the realm server?

**Review by ef4 — APPROVED** [review]
Approved based on discussion with some feedback.

**Review by lukemelia — APPROVED** [review]
LGTM!

**Pull request merged**
