### PR TITLE
Show module syntax errors in schema editor

### PR DESCRIPTION
**Pull request by jurgenwerk**
Display module syntax errors in the right side panel:

image

Video:

https://github.com/cardstack/boxel/assets/273660/b5396e32-7017-4d19-a891-c4f7669c263c

### CODE REVIEW

**Comment by tintinthong** [comment]
Is it possible to fit the error message in 

Screenshot 2023-12-18 at 09 55 46

**Comment by jurgenwerk** [comment]
@tintinthong you have to restart the realm server - you shouldn't be seeing the ansi color codes (things like `[36m`)

But yeah will make sure this gets a scroller if it becomes too wide

**Review by tintinthong — APPROVED** [review]
Noice! It solves a major UX pain point. 

I have 1 question, when inside an error state, you can no longer navigate out of the schema editor accordion? Was this intended behaviour??

**Comment by jurgenwerk** [comment]
> I have 1 question, when inside an error state, you can no longer navigate out of the schema editor accordion? Was this intended behaviour??

Can you demonstrate the problem? For me when I navigate to some other thing the schema editor changes

**Comment by tintinthong** [comment]
> > I have 1 question, when inside an error state, you can no longer navigate out of the schema editor accordion? Was this intended behaviour??
> 
> Can you demonstrate the problem? For me when I navigate to some other thing the schema editor changes

https://github.com/cardstack/boxel/assets/8165111/08c2bb40-ce5f-463f-86f1-7799f54f5bd5

It cud be that this was actually constrain you put on users to fix their code before looking at other things inside the accordion drawer. Which doesnt seem like a bad idea 

I still can navigate to other files

**Review by burieberry — APPROVED** [review]

**Comment by jurgenwerk** [comment]
For consistency I added the ability to roll up syntax errors with the accordion. It will make sense later when we add new items to the accordion

**Pull request merged**
