### PR TITLE
Setup realm server to use postgres indexing in staging and production

### PR DESCRIPTION
**Pull request by habdelra**
This PR adds env vars to waypoint hcl for using postgres as turns on the feature flag for using the postgres for indexing. I added postgresql into our ECS container so that we have easy access to `psql` for debugging our DB. I confirmed that I can login to our postgres DB from both our staging and production ECS containers already. so hopefully all that is left is to just turn on the flag.

I'll update our gitbook for instructions on logging into our ECS containers and running `psql`

### CODE REVIEW

**Comment by backspace** [comment]
hmm did you try deploying this to see if it worked? IIRC we don’t use Waypoint anymore, we should probably remove those files to reduce conusion.

**Comment by habdelra** [comment]
Yeah I was wondering about that. Agreed we should delete those waypoint files. 

I have not deployed this to see if it works, I think the only way is to merge this PR. I was planning to do that in the morning when everyone is around in case something goes wrong.

**Comment by backspace** [comment]
I think you could try it out like this:

#releases-internal | Cardstack - Discord 2024-05-06 16-48-09

Unless I’m misunderstanding something!

**Comment by backspace** [comment]
I opened #1229 to remove the Waypoint files.

**Comment by habdelra** [comment]
> I think you could try it out like this:
> 
> #releases-internal | Cardstack - Discord 2024-05-06 16-48-09
> Unless I’m misunderstanding something!

Nice! that didn’t occur to me

**Review by tintinthong — APPROVED** [review]

**Review by jurgenwerk — APPROVED** [review]

**Comment by habdelra** [comment]
looks like we are not quite ready on the infra side, the`pg_hba.conf` needs to be configured in RDS

**Comment by habdelra** [comment]
It looks like the test data that had `localhost:4201` in it was preventing the indexing from completing for some reason. I'm not too sure why that is, but we should track that down, as a bad URL should not interrupt indexing

**Comment by habdelra** [comment]
Also as a perf metric I'm seeing the cards grid search on staging take about 500ms. (not sure how much of that is spent in the db)

**Comment by habdelra** [comment]
Filed issue CS-6801 to look into the `localhost:4201` urls in card instances that break indexing in postgres

**Pull request merged**
