### PR TITLE
Add root to File Tree to show the realm being visualized

### PR DESCRIPTION
**Pull request by FadhlanR**
Ticket: CS-6064

Screenshot 2023-10-25 at 19 45 14

### CODE REVIEW

**Comment by habdelra** [comment]
Add test please (and also make sure to `await waitFor()`  the realm info span since it's inside a resource that is available async.)

**Comment by lukemelia** [comment]
@FadhlanR can we make this match the mock more closely in two ways? 1) preface the realm name with "in ", 2) less vertical padding on the realm name container. 
image

**Comment by FadhlanR** [comment]
@habdelra @lukemelia I've updated styles and tests. [269fb9c](https://github.com/cardstack/boxel/pull/758/commits/269fb9cf8f32b7b028f7d7526a316e9fab186136)

Screenshot 2023-10-26 at 15 32 32

**Review by habdelra — APPROVED** [review]

**Review by burieberry — COMMENTED** [review]
The font in the design is medium weight (500). Looks good otherwise

**Pull request merged**
