### PR TITLE
host: Add custom assertion for operator mode parameters

### PR DESCRIPTION
**Pull request by backspace**
This adds a custom assertion to use like this:

```
      assert.operatorModeParametersMatch(currentURL(), {
        stacks: [
          [
            {
              id: `${testRealmURL}Person/fadhlan`,
              format: 'isolated',
            },
          ],
          [
            {
              id: `${testRealmURL}Pet/mango`,
              format: 'isolated',
            },
          ],
        ],
        submode: Submode.Interact,
        fileView: 'inheritance',
        openDirs: { [testRealmURL]: ['Pet/'] },
      });
```

It’s meant to address the difficulty of reading assertion failures produced via string comparison with `currentURL()`, like this:

image

It encapsulates this series of assertions, CI failures for which you can see [here](https://github.com/cardstack/boxel/runs/17652145365):

`operatorMode=true`:

```
expected operatorModeEnabled=true
Expected:
    true

Result:
    false
```

`operatorModeState` exists:

```
in query string operatorModeEnabled=true&operatorModeNonstate=%7B%22stacks%22%3A%5B%5B%7B%22format%22%3A%22isolated%22%2C%22id%22%3A%22http%3A%2F%2Ftest-realm%2Ftest%2Findex%22%7D%5D%5D%2C%22submode%22%3A%22interact%22%7D, operatorModeState was 'null'
Expected:
    JSON string

Result:
    null
```

`operatorModeState` is JSON:

```
operatorModeState was {fileView:inheritance,openDirs:{},stacks:[[{format:isolated,id:http://test-realm/test/Person/fadhlan}]],submode:interact}, expected to be able to parse as JSON, got SyntaxError: Expected property name or '}' in JSON at position 1 (line 1 column 2)
Expected:
    valid JSON

Result:
    invalid JSON
```

`operatoModeState` matches the passed-in object:

```
expected current URL /?operatorModeEnabled=true&operatorModeState=%7B%22fileView%22%3A%22inheritance%22%2C%22openDirs%22%3A%7B%7D%2C%22stacks%22%3A%5B%5B%7B%22format%22%3A%22isolated%22%2C%22id%22%3A%22http%3A%2F%2Ftest-realm%2Ftest%2FPerson%2Ffadhlan%22%7D%5D%5D%2C%22submode%22%3A%22interact%22%7D to match operator mode state %7B%22stacks%22%3A%5B%5B%7B%22id%22%3A%22http%3A%2F%2Ftest-realm%2Ftest%2FPerson%2Fnot-fadhlan%22%2C%22format%22%3A%22isolated%22%7D%5D%5D%2C%22submode%22%3A%22interact%22%2C%22fileView%22%3A%22inheritance%22%2C%22openDirs%22%3A%7B%7D%7D
Expected:
    [object Object]

Result:
    [object Object]
```

This last is less useful in CI as the object is opaque, hence the query string fallback. But when testing locally the comparison is more clear:

image

### CODE REVIEW

**Review by habdelra — COMMENTED** [review]
:+1: I like the direction of this PR--it makes the assertions much easier to reason about

**Comment by backspace** [comment]
I added a `deepEqual` assertion on plain objects and the CI logs show the same thing:

```
Assertion failure without message - Actual: [object Object] Expected: [object Object]
```

That’s less than desirable but at least not something wrong with this in particular. I think I’ll add a comparison of the URL version too when it fails so at least something less opaque shows in CI.

**Comment by backspace** [comment]
> 👍 I like the direction of this PR--it makes the assertions much easier to reason about

thanks for checking it out @habdelra, any requests or additions? Otherwise I think it’s ready

**Comment by habdelra** [comment]
> > 👍 I like the direction of this PR--it makes the assertions much easier to reason about
> 
> thanks for checking it out @habdelra, any requests or additions? Otherwise I think it’s ready

I’d recommend merging this when you are ready.

**Review by habdelra — APPROVED** [review]

**Pull request merged**
