### PR TITLE
Default to non-thunk version of linksTo/linksToMany syntax

### PR DESCRIPTION
**Pull request by lukemelia**

### CODE REVIEW

**Comment by lukemelia** [comment]
Will we get into trouble with this for cyclic references, or is the only time we need the think when it is a self-reference to its own class?

**Comment by habdelra** [comment]
> Will we get into trouble with this for cyclic references, or is the only time we need the think when it is a self-reference to its own class?

The only time we need it is for self reference to its own class (it’s a JavaScript error otherwise)

**Comment by jurgenwerk** [comment]
There are other places in the codebase where `linksTo(() =>` pattern can be found (card definitions, code comments,...) - do these have to be changed too?

**Comment by habdelra** [comment]
> There are other places in the codebase where `linksTo(() =>` pattern can be found (card definitions, code comments,...) - do these have to be changed too?

It would be nice, maybe we can have the readme describe when you’d use a thunk as well…

**Comment by lukemelia** [comment]
> There are other places in the codebase where linksTo(() => pattern can be found (card definitions, code comments,...) - do these have to be changed too?

> It would be nice, maybe we can have the readme describe when you’d use a thunk as well…

I've pushed changes to address these ideas.

**Review by jurgenwerk — APPROVED** [review]

**Pull request merged**
