### PR TITLE
seperate thumbnail and icon block for clearer readability

### PR DESCRIPTION
**Pull request by lucaslyl**
linear: https://linear.app/cardstack/issue/ECO-150/seperate-icon-and-thumbnail-blocks-for-entity-display

### CODE REVIEW

**Comment by richardhjtan** [comment]
@lucaslyl I see there are some files which have changes to the seed realm, is that intentional?

**Comment by lucaslyl** [comment]
> @lucaslyl I see there are some files which have changes to the seed realm, is that intentional?

the file changes in seed realm is from commit [f22f7cf](https://github.com/cardstack/boxel/pull/1979/commits/f22f7cf23e3a53966905b2092032d50691f1d414) and [175a4d1](https://github.com/cardstack/boxel/pull/1979/commits/175a4d134ea96ca5f2a33de3318f809bf23a74d2) if not wrong

**Comment by richardhjtan** [comment]
> > @lucaslyl I see there are some files which have changes to the seed realm, is that intentional?
> 
> the file changes in seed realm is from commit [f22f7cf](https://github.com/cardstack/boxel/pull/1979/commits/f22f7cf23e3a53966905b2092032d50691f1d414) and [175a4d1](https://github.com/cardstack/boxel/pull/1979/commits/175a4d134ea96ca5f2a33de3318f809bf23a74d2) if not wrong

yes @lucaslyl  looks like github has some issue on display the only changes. When I compare between `main` in another page, there are only 13 file changes

**Comment by lucaslyl** [comment]
> > > @lucaslyl I see there are some files which have changes to the seed realm, is that intentional?
> > 
> > 
> > the file changes in seed realm is from commit [f22f7cf](https://github.com/cardstack/boxel/pull/1979/commits/f22f7cf23e3a53966905b2092032d50691f1d414) and [175a4d1](https://github.com/cardstack/boxel/pull/1979/commits/175a4d134ea96ca5f2a33de3318f809bf23a74d2) if not wrong
> 
> yes @lucaslyl looks like github has some issue on display the only changes. When I compare between `main` in another page, there are only 13 file changes

is this only happened in this pr?

**Comment by richardhjtan** [comment]
@lucaslyl so far yes, but it shouldn't be an issue to merge

**Pull request merged**
