### PR TITLE
host: Add scroll position persistence

### PR DESCRIPTION
**Pull request by backspace**
This adds a `RestoreScrollPosition` modifier which accepts `container` and `key` named arguments. It’s backed by a `ScrollPositionService` that manages persistence to local storage.

It’s only applied to the container for the file tree and inspector.

Criteria to satisfy:
* toggling to the other view and back again restores the scroll position
* `ScrollIntoView` should only take precedence over persisted scroll position after an initial render
  * this means uses of it need `container` and `key` if they should respect this
* refreshing restores the scroll position
* persistence is lost for a container when its focus has changed
  * file tree will not remember the position for the previous file
    * this means positions are not realm-specific but if this is desired it could be made part of the `container` value
  * inspector will not remember the position for the previous detail element

Here’s me exercising it: scrolling to the bottom of both panes is restored when switching between them, scrolling into view still works, and refreshing restores the position.

https://github.com/cardstack/boxel/assets/43280/1aadb844-8460-42a9-a1dc-d3ec6b6f2952

## Restoration lag

It’s harder to notice in these recordings vs [in practice](https://hostmemory-scroll-files-cs-6033.boxel-host-preview.stack.cards/?operatorModeEnabled=true&operatorModeState=%7B%22codePath%22%3A%22https%3A%2F%2Frealms-staging.stack.cards%2Fdrafts%2Findex.json%22%2C%22codeSelection%22%3A%7B%7D%2C%22fileView%22%3A%22inspector%22%2C%22openDirs%22%3A%7B%7D%2C%22stacks%22%3A%5B%5B%7B%22format%22%3A%22isolated%22%2C%22id%22%3A%22https%3A%2F%2Frealms-staging.stack.cards%2Fdrafts%2Findex%22%7D%5D%5D%2C%22submode%22%3A%22code%22%7D) but there’s a noticeable lag sometimes updating the scroll position that I couldn’t figure out how to eliminate, a bit more visible here:

screencast 2023-12-04 14-32-00

The way I chose to decide when to trigger the scrolling was a debounced mutation observer callback, so that necessarily means a delay after things have settled to then scroll.

Another approach I considered would be to insert a sentinel component at the end that could trigger the scroll but I couldn’t figure out how to do that without the child components needing to change, which seemed inappropriate. This solution allows the modifier to be used on the scrolling element and the only thing that needs to change within the children is the addition of the `container` and `key` for `ScrollIntoView`.

### CODE REVIEW

**Comment by jurgenwerk** [comment]
I find it a bit unexpected that clicking the item in the file tree will scroll it to the middle. Is this intentional?

https://github.com/cardstack/boxel/assets/273660/743cce01-9e01-4dac-9a94-2e6ebcc8c600

**Comment by backspace** [comment]
> I find it a bit unexpected that clicking the item in the file tree will scroll it to the middle. Is this intentional?

Definitely not, thanks for pointing this out, I didn’t notice this change.

**Review by burieberry — COMMENTED** [review]
I noticed the slight lag, but otherwise looks good

**Comment by habdelra** [comment]
> This adds a `RestoreScrollPosition` modifier which accepts `container` and `key` named arguments. It’s backed by a `ScrollPositionService` that manages persistence to local storage.
> 
> It’s only applied to the container for the file tree and inspector.
> 
> Criteria to satisfy:
> 
> * toggling to the other view and back again restores the scroll position
> * `ScrollIntoView` should only take precedence over persisted scroll position after an initial render
>   
>   * this means uses of it need `container` and `key` if they should respect this
> * refreshing restores the scroll position
> * persistence is lost for a container when its focus has changed
>   
>   * file tree will not remember the position for the previous file
>     
>     * this means positions are not realm-specific but if this is desired it could be made part of the `container` value
>   * inspector will not remember the position for the previous detail element
> 
> Here’s me exercising it: scrolling to the bottom of both panes is restored when switching between them, scrolling into view still works, and refreshing restores the position.
> 
>  screencast.2023-12-04.14-32-00.mp4 
> ## Restoration lag
> It’s harder to notice in these recordings vs [in practice](https://hostmemory-scroll-files-cs-6033.boxel-host-preview.stack.cards/?operatorModeEnabled=true&operatorModeState=%7B%22codePath%22%3A%22https%3A%2F%2Frealms-staging.stack.cards%2Fdrafts%2Findex.json%22%2C%22codeSelection%22%3A%7B%7D%2C%22fileView%22%3A%22inspector%22%2C%22openDirs%22%3A%7B%7D%2C%22stacks%22%3A%5B%5B%7B%22format%22%3A%22isolated%22%2C%22id%22%3A%22https%3A%2F%2Frealms-staging.stack.cards%2Fdrafts%2Findex%22%7D%5D%5D%2C%22submode%22%3A%22code%22%7D) but there’s a noticeable lag sometimes updating the scroll position that I couldn’t figure out how to eliminate, a bit more visible here:
> 
> screencast 2023-12-04 14-32-00 [ screencast 2023-12-04 14-32-00 ](https://private-user-images.githubusercontent.com/43280/287827197-704ea300-6062-489b-9fd5-4b7e975e72d6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MDQ0MjAsIm5iZiI6MTcwMTgwNDEyMCwicGF0aCI6Ii80MzI4MC8yODc4MjcxOTctNzA0ZWEzMDAtNjA2Mi00ODliLTlmZDUtNGI3ZTk3NWU3MmQ2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE5MjIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZTMzYzdhYjM1Y2IxNWZkOTQwN2M0NGRhYWU4MGRjMTJlYTQzZmI5Yzg0ZDY2YzgwY2MxMTBkZjhiMThjMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ae9c6dFR8G5Me3UhwDR-xNSw_T8qUwdzdl3o1gPt78U) [ ](https://private-user-images.githubusercontent.com/43280/287827197-704ea300-6062-489b-9fd5-4b7e975e72d6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MDQ0MjAsIm5iZiI6MTcwMTgwNDEyMCwicGF0aCI6Ii80MzI4MC8yODc4MjcxOTctNzA0ZWEzMDAtNjA2Mi00ODliLTlmZDUtNGI3ZTk3NWU3MmQ2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE5MjIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZTMzYzdhYjM1Y2IxNWZkOTQwN2M0NGRhYWU4MGRjMTJlYTQzZmI5Yzg0ZDY2YzgwY2MxMTBkZjhiMThjMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ae9c6dFR8G5Me3UhwDR-xNSw_T8qUwdzdl3o1gPt78U)
> 
> The way I chose to decide when to trigger the scrolling was a debounced mutation observer callback, so that necessarily means a delay after things have settled to then scroll.
> 
> Another approach I considered would be to insert a sentinel component at the end that could trigger the scroll but I couldn’t figure out how to do that without the child components needing to change, which seemed inappropriate. This solution allows the modifier to be used on the scrolling element and the only thing that needs to change within the children is the addition of the `container` and `key` for `ScrollIntoView`.

another thought on how to deal with the lag would be to hide it by overlaying a "mask" element on the file tree during the debounce and the removing the mask after the scroll position has been updated. maybe show a busy indicator on teh mask or maybe nothing at all. i guess you could decide which is worse--show a lag or show nothing for a moment.

**Comment by backspace** [comment]
> another thought on how to deal with the lag would be to hide it by overlaying a "mask" element on the file tree during the debounce and the removing the mask after the scroll position has been updated. maybe show a busy indicator on teh mask or maybe nothing at all. i guess you could decide which is worse--show a lag or show nothing for a moment.

That sounds like it might feel nicer, I’ll open an issue for further investigation, thanks.

**Pull request merged**
