### PR TITLE
Tool tip for less ambiguous name in schema editor

### PR DESCRIPTION
**Pull request by tintinthong**
https://github.com/cardstack/boxel/assets/8165111/07d36d69-2b9d-4b84-a400-349a9d83c50d

I put the placement of tool tip at the bottom bcos it looks better

When codeRef is available 

Screenshot 2023-10-31 at 9 01 10 PM

When codeRef is unavailable 

Screenshot 2023-10-31 at 9 00 04 PM

### CODE REVIEW

**Comment by tintinthong** [comment]
~Hold off review. I see something not working as expected~

**Comment by tintinthong** [comment]
There is a loader related issue. Let me write it down here to explain for clarity

- The `Base` pill should have a codeRef but not just any codeRef -- a resolved one. One that resolves to `{module, name}`
- This is not always guaranteed, particularly if `BaseDef` is not used in one of the modules within the drafts workspace. 
- If `BaseDef` is not imported somewhere to trigger an indexing of the modules identities, the codeRef would just be `{ancestorOf}` 

so this is one of those situations whereby the resolved code ref only appears after you've visited the module. What I have done is to keep `getCodeRef` as returning either the resolvedCodeRef | undefined

**Comment by tintinthong** [comment]
Ok Ready for review now

**Review by habdelra — COMMENTED** [review]
add tests please

**Comment by tintinthong** [comment]
> add tests please

Added test here https://github.com/cardstack/boxel/pull/781/commits/6eb120d8a6a888f13c9822c302024a15367758f7

**Review by FadhlanR — APPROVED** [review]

**Pull request merged**
