### PR TITLE
Add custom realm URL response header

### PR DESCRIPTION
**Pull request by habdelra**
This is to assist describing the realm URL for files loaded from realm using the application/vnd.card+source accept header

### CODE REVIEW

**Review by lukemelia — APPROVED** [review]
The arguments signature of createResponse seems kind of haphazard to me, but this looks good otherwise.

**Comment by burieberry** [comment]
> The arguments signature of createResponse seems kind of haphazard to me, but this looks good otherwise.

createResponse had the same signature as Fetch API's Response class

**Review by burieberry — APPROVED** [review]

**Comment by habdelra** [comment]
> The arguments signature of createResponse seems kind of haphazard to me, but this looks good otherwise.

The challenge is is that we use this for streaming responses too, which is why I made it null or a string.

**Comment by habdelra** [comment]
> > The arguments signature of createResponse seems kind of haphazard to me, but this looks good otherwise.
> 
> createResponse had the same signature as Fetch API's Response class

we could modify all the call sites to include the custom header instead, but my fear is that if we added a new response we might forget to set the custom header.

**Review by jurgenwerk — APPROVED** [review]

**Pull request merged**
