### PR TITLE
host: Move URL search into default search

### PR DESCRIPTION
**Pull request by backspace**
This adds the ability to enter URLs into search instead of requiring a separate field:

https://github.com/cardstack/boxel/assets/43280/9ceaf246-bb8f-42a5-826b-2aebd2fe7b35

How it was:

Boxel 2023-11-15 14-18-11

Implementation notes:
* it doesn’t start trying to fetch a URL until it can be parsed as a URL
* “No card found at $URL” is an arbitrary wording choice
* as is “Card found at $URL”, I’m open to suggestions
* the now-orphaned “Cancel” button seems weird but since the search field takes up the entire top using the X close button featured on the card catalog modal didn’t seem suitable

I originally planned to convert the card catalog search modal in this way as well but I encountered more complexity than I expected and will address that separately.

### CODE REVIEW

**Comment by backspace** [comment]
The failing test is failing on `main` so it seems unrelated!

**Review by habdelra — APPROVED** [review]
looks great. i think the wording choices are totally fine

**Review by burieberry — COMMENTED** [review]
This looks good. Not a blocker for this PR but I noticed the x icon that appears in the search input looks a little off (probably browser style). Maybe we can remove it, or if that function is desired, replace the icon with our x icon and have it not overlap the validation icons

**Comment by backspace** [comment]
> This looks good. Not a blocker for this PR but I noticed the x icon that appears in the search input looks a little off (probably browser style). Maybe we can remove it, or if that function is desired, replace the icon with our x icon and have it not overlap the validation icons

ya I’m starting to wonder if it even makes sense to use `type="search"`, which is what produces this. I added `autocomplete="off"` on this because it was showing up in a weird way:

Monosnap 2023-11-17 10-58-43

The now merged-in `SearchInput` didn’t use `type="search"`, maybe that makes the most sense.

**Pull request merged**
