### PR TITLE
Avoid stampede of retrieving the cardAPI when loader changed.

### PR DESCRIPTION
**Pull request by lukemelia**
I had observed that Code Mode was lagging for me on staging, and via the Chrome inspector found that I had 34,408 ember-concurrency task instances in a 'running' state and that they were all the getAPI task

It eventually recovered after 5-10 minutes.

This commit refactors getAPI to an async method and adds a loading promise cache to avoid making unneeded calls to loader.import

### CODE REVIEW

**Comment by backspace** [comment]
How many loaders does one expect to be present? The number is climbing for me with every operation:

Boxel 2024-01-10 13-32-58

I’m definitely not familiar with this area of the code but my instinct is that these would be more long-lived 🤔

**Comment by lukemelia** [comment]
Whoops, I didn't mean to leave that logging in there. I'll fix that. I believe the loader is discarded any time there is a change to a card/field definition.

**Review by backspace — APPROVED** [review]
👍🏻 thanks for the explanation, this change seems right to me but I think Hassan should give the true approval 🤓

**Review by habdelra — APPROVED** [review]
looks good!

**Pull request merged**
