### PR TITLE
Load dist for fastboot directly from deployed s3/cloudfront

### PR DESCRIPTION
**Pull request by habdelra**
This removes the need to have a zip of the host app dist necessary for fastboot. Instead we just grab the assets directly off of the hosted env in s3/cloudront

TODO:
- [x] test in hosted env
- [x] test locally

### CODE REVIEW

**Comment by backspace** [comment]
Maybe `scripts/fetch-dist` and its associated `package.json` scripts are obsolete now?

**Comment by habdelra** [comment]
@backspace yeah, i think i removed them in this PR. i can double check tho

**Comment by backspace** [comment]
hah no you definitely did, sorry!!

**Comment by backspace** [comment]
oh `fetch-dist` is still [referenced in some `setup` scripts](https://github.com/cardstack/boxel-motion/pull/273/files#diff-62bb6b1905da7327279cb4451db5727204c1efae025a16b8770c830064bfa233R54-R55)

**Comment by habdelra** [comment]
@backspace good catch!--i think actually we still need that, not for fastboot but for host asset serving. We'll continue to need that until this ticket is performed https://linear.app/cardstack/issue/CS-5404/realm-server-should-serve-host-assets-from-server-that-is-deadicated (I'll need to restore fetch-dist in this PR).

**Pull request merged**
