### PR TITLE
Fix flicker from declarations

### PR DESCRIPTION
**Pull request by tintinthong**
Look at LHS & RHS

**Before**

https://github.com/cardstack/boxel/assets/8165111/8ba5a99d-62b6-4baa-8d6d-90787218857a

**After**

https://github.com/cardstack/boxel/assets/8165111/ce13d8e7-865b-444f-a471-8978e21530ad

### CODE REVIEW

**Review by FadhlanR — APPROVED** [review]

**Comment by tintinthong** [comment]
bleurgh looks like this broke a lot of things

**Comment by jurgenwerk** [comment]
What broke?

**Comment by tintinthong** [comment]
> What broke?

The thing which broke was. When I edit the file, the "in-this-file" panel disappears because I returned an empty array because of my first change. 

> My new change

My new change which I think wud work IS. to track an internal url variable so that module contents knows when its loading a new module. If it loads a new module, its ok to return [] empty declarations. When its loading the same module because you edited a file, the declarations surfaced will be that of the stale value until everything is loaded in which case, the data is swapped to the new value

**Comment by tintinthong** [comment]
@FadhlanR @jurgenwerk sorry I have to re-request review because my solution fundamentally changed

**Review by jurgenwerk — APPROVED** [review]

**Pull request merged**
