### PR TITLE
Fix markdown format in ai panel for received messages

### PR DESCRIPTION
**Pull request by burieberry**
Before: 
before

After:
after

### CODE REVIEW

**Review by habdelra — COMMENTED** [review]
can we write a test for this? there were originally matrix tests that test that markdown is rendered correctly, i'd like to see that sort of thing added here as well

**Comment by burieberry** [comment]
> can we write a test for this? there were originally matrix tests that test that markdown is rendered correctly, i'd like to see that sort of thing added here as well

This is a little strange. That test is still there and is passing actually. This is for rendering the response that's coming from the ai bot. I'm not sure how to replicate that in a test but I'll take a look.

Here's an example from staging:
staging

**Comment by habdelra** [comment]
is there a mock we can use? maybe @IanCal knows?

**Comment by burieberry** [comment]
> is there a mock we can use? maybe @IanCal knows?

Added a test for this 👍

**Pull request merged**
