### PR TITLE
Add a dropdown to cards-grid card to order by title or updated at 

### PR DESCRIPTION
**Pull request by jurgenwerk**
- Allow ordering by a non-card attribute field (`lastModified` in this case)
- Use it to sort by lastModified in index card (in addition to sorting by `title`)

image

https://github.com/user-attachments/assets/d8430b2d-1b55-44e9-aced-2d34c2c7e97d

### CODE REVIEW

**Review by FadhlanR — APPROVED** [review]
Great! I'll rebase [PR](https://github.com/cardstack/boxel/pull/1559), so I can reuse the top-bar class.

**Review by lukemelia — APPROVED** [review]

**Comment by lukemelia** [comment]
I'd like for @habdelra to review before we merge.

**Review by habdelra — APPROVED** [review]
looks good

**Comment by jurgenwerk** [comment]
Thanks!

**Pull request merged**
