### PR TITLE
Remove unnecessary CSS in prerendered cards payload

### PR DESCRIPTION
**Pull request by jurgenwerk**
Previously, the CSS for prerendered cards was fetched by looking at the card instance `deps` field and looking up `css` entries for them in `boxel_index` table. This returned a lot of unnecessary CSS, especially when we only request the basic `CardDef` template (for example cards in in cards grid).

With this change, the CSS is is narrowed down to cover only the card type that we want (i.e. the value of `on` filter - more details in this PR: https://github.com/cardstack/boxel/pull/1436). We take the css from the module specified in the `on` filter value, and looking up the css entries for module's `deps`. 

The response also changed, specifically `relationships` was removed because we no longer associate CSS with the instances but rather with module used in the filter to fetch the instances.

Previously:

```
{
  "data": [
    {
      "type": "prerendered-card",
      "id": "http://127.0.0.1:4444/jimmy",
      "attributes": {
        "html": "embedded template"
      },
      "relationships": {
        "prerendered-card-css": {
          "data": [
            {
              "type": "prerendered-card-css",
              "id": "http://127.0.0.1:4444/fancy-person"
            },
            {
              "type": "prerendered-card-css",
              "id": "http://127.0.0.1:4444/person"
            }
          ]
        }
      }
    }
  ],
  "included": [
    {
      "type": "prerendered-card-css",
      "id": "http://127.0.0.1:4444/fancy-person",
      "attributes": {
        "content": ".fancy-border[data-scopedcss-b9c3801d7f-4c0a5cc85e] {\n border: 1px solid pink;\n }"
      }
    },
    {
      "type": "prerendered-card-css",
      "id": "http://127.0.0.1:4444/person",
      "attributes": {
        "content": ".border[data-scopedcss-2a598dec83-c0485838e3] {\n border: 1px solid red;\n }"
      }
    }
  ],
  "meta": {
    "page": {
      "total": 1,
      "realmVersion": 1
    }
  }
}
```

Now:

```
{
  "data": [
    {
      "type": "prerendered-card",
      "id": "http://127.0.0.1:4444/jimmy",
      "attributes": {
        "html": "embedded template for Jimmy"
      },
    },
    {
      "type": "prerendered-card",
      "id": "http://127.0.0.1:4444/jonathan",
      "attributes": {
        "html": "embedded template for Jonathan"
      },
    }
  ],
  "included": [
    {
      "type": "prerendered-card-css",
      "id": "https://cardstack.com/base/card-api",
      "attributes": {
        "source": ".default-embedded-template { ... }"
      }
    },
  ],
  "meta": {
    "page": {
      "total": 1,
      "realmVersion": 1
    }
  }
}
```

### CODE REVIEW

**Review by habdelra — APPROVED** [review]
:+1:

**Review by FadhlanR — APPROVED** [review]

**Comment by lukemelia** [comment]
@jurgenwerk without the relationships, how will we know which CSS to show with each card?

**Comment by habdelra** [comment]
That’s a good point. The json-api spec maintains that included resources are included because there is a relationship that correlates to them. It doesn’t make sense to have included resources “just because”, these includes then just become orphans since nothing from the `data` part of the document consumes them.

**Comment by jurgenwerk** [comment]
The reason `relationships` were removed is because in this implementation the returned CSS will always be the same for all cards in the response since the CSS is dictated by the card type value in the filter. So if the filter specifies to only get `FancyPerson` cards then the only CSS that we need to return is the one for `FancyPerson` (and its deps). If the on filter is missing, then we fall back to the embedded template and CSS for `CardDef`. This means all cards would have the same relationship to the included CSS items, which seemed redundant to specify. I do realize now this is a deviation from the json:api spec, I can add that back. Let me know if you have any other thoughts related to this description of the implementation.

**Comment by jurgenwerk** [comment]
Conclusion from the meeting: add relationships back so that they are explicit rather than implicit. Could spare us problems in the future if we'll see a need for cards in the result set to have different css

**Pull request merged**
