### PR TITLE
host: Add Percy for code route

### PR DESCRIPTION
**Pull request by backspace**
This adds snapshots for two code routes, there will probably be more as the feature is expanded. There’s a new function to wait for expected colours of syntax highlighting to prevent spurious diffs like this:

screencast 2023-08-22 09-38-12

I also added a test override to force wrapping as it was rendering inconsistently:

screencast

These are unsightly to me but better than Percy noise IMO, if anyone has suggestions on improvement, let me know!

### CODE REVIEW

**Review by lukemelia — APPROVED** [review]

**Comment by backspace** [comment]
This is definitely not ready, when I had it before it had a lot of spurious diffs because of font and colour differences 😳

**Comment by backspace** [comment]
well I guess seven successive runs without a spurious diff is sufficient, I’m surprised to see no problems, but we can revisit if some start showing up

**Comment by backspace** [comment]
hah yes just as I was about to believe the problem was gone, the syntax highlighting disappeared

Build #691 - Cardstack - Percy | Visual testing as a service 2023-08-21 16-46-44

**Comment by backspace** [comment]
The colour assertions are somewhat working as intended but the wrinkle now is that the diffs show that the snapshot is happening while syntax highlighting is still in progress, so I’ll change the waiting to be for colours at the end instead of the beginning 🥴 

screencast 2023-08-22 09-38-12

**Review by burieberry — APPROVED** [review]
nice

**Pull request merged**
