### PR TITLE
Move production deployment targets to boxel.ai

### PR DESCRIPTION
**Pull request by backspace**

### CODE REVIEW

**Comment by lukemelia** [comment]
@backspace Should this PR be closed?

**Comment by backspace** [comment]
> @backspace Should this PR be closed?

no, I didn’t realise I hadn’t submitted it for review, thanks.

**Review by burieberry — COMMENTED** [review]
Is this related to the failure to deploy to staging preview in latest PRs? They show a `no such bucket` error. Would this PR resolve that?

**Comment by backspace** [comment]
> Is this related to the failure to deploy to staging preview in latest PRs? They show a `no such bucket` error. Would this PR resolve that?

assuming you mean production, yes, this should fix that. You can see the preview deployment works in this PR.

**Review by burieberry — APPROVED** [review]
assuming the aws cloudfront code is not supposed to be a secret, looks good to me

**Pull request merged**
