### PR TITLE
Adjust prerendered endpoint to return css encoded urls 

### PR DESCRIPTION
**Pull request by jurgenwerk**
After the realization we have special urls with encoded css saved  in `deps` field of the index table, which look like this:

`http://localhost:4201/drafts/post.gts.CiAgICAgICAgLmNvbnRhaW5lcltkYXRhLXNjb3BlZGNzcy1kMDNhYWQ3ZTg3LTYzODc4YTM0NGZdIHsKICAgICAgICAgIHBhZGRpbmc6IHZhcigtLWJveGVsLXNwLXhsKTsKICAgICAgICB9CiAgICAgIA%3D%3D.glimmer-scoped.css` (the encoded part in between is the CSS)

... we abandoned the approach of querying entries of `css` type in the boxel index table, since the CSS code mentioned above is also persisted in a cross-realm manner (when indexing modules that inherit from modules that live in foreign realms, it saves css urls of all modules in the dependency chain in `deps`) which is not the case with entries of `css` type in the boxel index table.

~~So now, the prerendered card response will look like this:~~

```
{
  "data": [
    {
      "type": "prerendered-card",
      "id": "http://127.0.0.1:4444/jimmy",
      "attributes": {
        "html": "embedded template"
      },
      "relationships": {
        "prerendered-card-css": {
          "data": [
            {
              "type": "prerendered-card-css",
              "id": "http://localhost:4201/drafts/fancy-person.gts.<ENCODED CSS>.glimmer-scoped.css"
            },
            {
              "type": "prerendered-card-css",
              "id": "http://localhost:4201/drafts/person.gts.<ENCODED CSS>.glimmer-scoped.css"
            },
            {
              "type": "prerendered-card-css",
              "id": "https://cardstack.com/base/card-api.gts.<ENCODED CSS>.glimmer-scoped.css"
            }, ... 
          ]
        }
      }
    }
  ]
  ```

Update after https://github.com/cardstack/boxel/pull/1469/commits/4df90b30bdda05d4bc38a0d4d462e93ab5563cf8:
  
  ```
{
  "data": [
    {
      "type": "prerendered-card",
      "id": "http://127.0.0.1:4444/jimmy",
      "attributes": {
        "html": "embedded template"
      },
    }],
    "meta": {
      "scopedCssUrls": ["http://localhost:4201/drafts/fancy-person.gts.<ENCODED CSS>.glimmer-scoped.css", "http://localhost:4201/drafts/person.gts.<ENCODED CSS>.glimmer-scoped.css", "https://cardstack.com/base/card-api.gts.<ENCODED CSS>.glimmer-scoped.css"]
      "page": {
        total: 1,
        realmVersion: 1
       }
    }
}
```
  

These urls will then be `import`ed  by the loader service's loader, and that request will be intercepted by [maybeHandleScopedCSSRequest](https://github.dev/cardstack/boxel/blob/337a7e409d11c402427b4a88f4a6d96652136605/packages/runtime-common/scoped-css.ts), which will inject the style into the DOM.

### CODE REVIEW

**Comment by lukemelia** [comment]
@jurgenwerk I think we can & should start with this, but it is going to create a lot of redundancy in the payload, since the URLs contain the CSS content and they need to be duplicated for each card in this scheme. @ef4 was suggesting we consider using meta for this.

**Comment by jurgenwerk** [comment]
Hm, another option I was thinking about to help getting rid of the redundancy would be to bring back `included` like we had it in previous implementations when we were serving the actual css source code. Before serving the response we could hash these urls to obtain some kind of an ID for each individual css url (module id is not enough because there can be several css urls for one module), and put these ids in the `relationships`. We could then look up css urls for every instance in `included`.

**Comment by jurgenwerk** [comment]
We discussed this with @lukemelia on a call - we can add a list of unique css urls as an entry in `meta`, and drop `relationships` and `included`.

**Review by habdelra — APPROVED** [review]
the meta solution discussed sounds fine. looks good!

**Review by lukemelia — APPROVED** [review]

**Pull request merged**
