### PR TITLE
Fix: Skill cards on messages don't update if skill card is updated

### PR DESCRIPTION
**Pull request by FadhlanR**
We used `SkillCard` instances in the `RoomResource` state. Due to this, the skill cards would not update if there were any changes. To fix this issue, I constructed the skill card resource in the room component and used it in the pill menu component, ensuring that the pill items remain reactive.

### CODE REVIEW

**Comment by tintinthong** [comment]
Hey @FadhlanR is it easier if we took skills out of the RoomState class and put it on the room resource? Or does that open a whole can of worms?

**Review by lukemelia — COMMENTED** [review]
This doesn't feel right to me. The API modifications moving from SkillCard to CardResource make the APIs more confusing to understand. Perhaps there is another way to think about this? We can ask @ef4 on Monday too.

**Comment by FadhlanR** [comment]
@tintinthong @lukemelia Thanks for the feedback! I decided to use a different approach that I believe is simpler. Instead of updating the `RoomState`, I left it as is and constructed the skill card resource directly in the room component. This approach avoids confusion from API updates and still maintains reactivity for the skill cards.

**Comment by tintinthong** [comment]
Im not a fan of this map of card resources. My initial guess is that its better to make a resource which is function of all these other resources. I would defer to @ef4 to help review this.

**Comment by jurgenwerk** [comment]
@FadhlanR what is the status on this one? I see in the ticket there was a new decision made a week ago in the sprint planning, does it affect this implementation? Ticket also has "needs design" and is blocked by 2 tickets so I'm unsure if this is reviewable?

**Comment by FadhlanR** [comment]
> @FadhlanR what is the status on this one? I see in the ticket there was a new decision made a week ago in the sprint planning, does it affect this implementation? Ticket also has "needs design" and is blocked by 2 tickets so I'm unsure if this is reviewable?

@jurgenwerk this PR is blocked by this [ticket](https://linear.app/cardstack/issue/CS-7113/review-roomskills-architecture-and-make-recommendations).

**Comment by lukemelia** [comment]
Closing as we are taking a different approach with this.

**Pull request closed without merging**
