### PR TITLE
Refactor card chooser to allow user to specify realm to create new card

### PR DESCRIPTION
**Pull request by habdelra**
This PR refactors the card chooser so that you can choose the realm of a newly created card. 

Note that for now please don't choose to create a new linked card in a realm that is different than the realm of the consuming card. This will result in an error doc in the index for the consuming card. A solution for this scenario is forthcoming.

new-card

### CODE REVIEW

**Review by backspace — APPROVED** [review]
I exercised this successfully in the preview deployment

I have a mild concern about the lack of feedback between choosing to create a new card and the new card appearing. I had a moment of “is anything happening?” and checking the console because I ran into several brokennesses on the way to testing this out. Your GIF shows a similar delay. Is there any way to indicate a sense that something is happening between the pressing and the rendering?

**Comment by habdelra** [comment]
> I exercised this successfully in the preview deployment
> 
> I have a mild concern about the lack of feedback between choosing to create a new card and the new card appearing. I had a moment of “is anything happening?” and checking the console because I ran into several brokennesses on the way to testing this out. Your GIF shows a similar delay. Is there any way to indicate a sense that something is happening between the pressing and the rendering?

there is a realm indexing indicator (the icon in the header), it starts pulsing--but that might be too subtle to notice. This delay is not new though, it existed in the previous implementation too.

**Comment by backspace** [comment]
> there is a realm indexing indicator (the icon in the header), it starts pulsing--but that might be too subtle to notice. This delay is not new though, it existed in the previous implementation too.

ah I see it now, I’d naturally look to the “Link Friend” area for a progress indicator, but understood re this being an existing thing, it just changes immediately when you choose an existing card vs create a new one.

**Comment by habdelra** [comment]
Maybe we can request some design feedback during the sprint demo around making a better interstitial state

**Pull request merged**
