### PR TITLE
Implement the new design for the card overlay

### PR DESCRIPTION
**Pull request by FadhlanR**
Cards grid item overlay:

https://github.com/user-attachments/assets/10b37840-3e05-41e3-bc20-96f124df3908

Field overlay:

https://github.com/user-attachments/assets/41e457eb-bcbe-4eba-9e37-aba99762dffc

### CODE REVIEW

**Review by burieberry — COMMENTED** [review]
- I'm not sure how to replicate, but after using the app for a while (maybe after creating a card?), I come across a state where hovering over an item on the index card does not display the overlays. The errors here might be relevant to this:
errors

- I don't see the pencil icon. I think we need to add it when user has write permissions.
- Styling tweaks:
-Highlight color for icon button background should be --boxel-cyan
-Box shadow is missing from the overlay items
-Selected state of the selection icon has a checkmark in one of the designs. Unclear from the designs if the checkmark remains visible while not hovering on the selected item.

**Comment by FadhlanR** [comment]
> * I'm not sure how to replicate, but after using the app for a while (maybe after creating a card?), I come across a state where hovering over an item on the index card does not display the overlays. The errors here might be relevant to this:
> 
> errors
> * I don't see the pencil icon. I think we need to add it when user has write permissions.
> * Styling tweaks:
>   -Highlight color for icon button background should be --boxel-cyan
>   -Box shadow is missing from the overlay items
>   -Selected state of the selection icon has a checkmark in one of the designs. Unclear from the designs if the checkmark remains visible while not hovering on the selected item.

@burieberry Thanks for the comment. I've addressed most of the points. Could you please share the screenshot of the missing box shadow? Also, we need @lukemelia’s input on the following: “The selected state of the selection icon has a checkmark in one of the designs. It's unclear from the designs whether the checkmark remains visible when not hovering over the selected item.”

https://github.com/user-attachments/assets/27628b49-78aa-4ec3-a51f-c788c04e727f

**Comment by lukemelia** [comment]
@FadhlanR @burieberry I think that a checked checkbox should indeed stay visible beyond hover.

**Comment by FadhlanR** [comment]
> @FadhlanR @burieberry I think that a checked checkbox should indeed stay visible beyond hover.

Updated

Screenshot 2024-08-19 at 21 09 19

**Comment by FadhlanR** [comment]
> > * I'm not sure how to replicate, but after using the app for a while (maybe after creating a card?), I come across a state where hovering over an item on the index card does not display the overlays. The errors here might be relevant to this:
> > 
> > errors
> > * I don't see the pencil icon. I think we need to add it when user has write permissions.
> > * Styling tweaks:
> >   -Highlight color for icon button background should be --boxel-cyan
> >   -Box shadow is missing from the overlay items
> >   -Selected state of the selection icon has a checkmark in one of the designs. Unclear from the designs if the checkmark remains visible while not hovering on the selected item.
> 
> @burieberry Thanks for the comment. I've addressed most of the points. Could you please share the screenshot of the missing box shadow? Also, we need @lukemelia’s input on the following: “The selected state of the selection icon has a checkmark in one of the designs. It's unclear from the designs whether the checkmark remains visible when not hovering over the selected item.”
> 
>  Screen.Recording.2024-08-19.at.14.30.07.mov

Added box shadow.

Screenshot 2024-08-19 at 21 22 15

**Review by burieberry — APPROVED** [review]

**Pull request merged**
