### PR TITLE
Add lodash debouncing to message sending from AI bot

### PR DESCRIPTION
**Pull request by IanCal**
Loadash debounce supports a "maxWait" parameter https://lodash.com/docs#debounce

This means that we can safely call repeatedly as fast as we want, and regular debounce logic avoids a huge number of events, but maxWait also means that we send messages regularly (which is what we want). Without the maxWait we'd only send one message right at the end.

I don't know what's happening with pnpm-lock, I get different results in a totally clean branch and seem to be using the right version of pnpm. Ember modifiers and prettier changes?

### CODE REVIEW

**Comment by habdelra** [comment]
I think you might be leaking async in your tests. Consider the scenario a test finishes before the debounce is triggered, and after the test is done then debounce kicks off. You should expose a function `flush()` that awaits the message promises which is called in the afterEach of your tests. 

The general rule of thumb is that anytime an async function is called synchronously you need to catch async leaks in tests. I’ve never encountered a scenario were this was not the case (and every time I forgot I was cursed with flaky tests)

**Comment by IanCal** [comment]
> I think you might be leaking async in your tests. Consider the scenario a test finishes before the debounce is triggered, and after the test is done then debounce kicks off. You should expose a function `flush()` that awaits the message promises which is called in the afterEach of your tests.
> 
> The general rule of thumb is that anytime an async function is called synchronously you need to catch async leaks in tests. I’ve never encountered a scenario were this was not the case (and every time I forgot I was cursed with flaky tests)

That's a good point - there's not currently any testing that captures sending messages back, but I shouldn't add something that makes adding testing around this harder. After we merge the refactor in #1254 I can revisit this and the Assistant class will give a place we can add a flush to.

**Review by jurgenwerk — APPROVED** [review]
Neat solution with the debounce

**Comment by IanCal** [comment]
replaced with #1296

**Pull request closed without merging**
