### PR TITLE
Add capabilities for working with LinksTo fields [CS-6675]

### PR DESCRIPTION
**Pull request by burieberry**
- [x] I can ask the AI to link to a different card for the fields. (OK if the AI asks you to search for cards of the correct type).
add-card-name-1

Asking an edit via card name and field name:
edit-card-name-2

Asking an edit and sharing the card in the attachment:
edit-via-shared-card

- [x] I can ask the AI to remove a linked card by the content (e.g. title) of the linked card
making-edit-1

- [x] I can ask the AI to remove (unlink) a linked card by field name
remove-all

Asking to remove all linked cards:
remove-all-linked-cards

Adding multiple linksTo field values via given URLs:
add-linksTo-1
add-linksTo-2

Making an edit to an attribute and a linksTo field at the same time:
edit-1

### CODE REVIEW

**Comment by backspace** [comment]
I’m not sure if I’m doing something wrong or not understanding the scope of this PR but I experienced two problems exercising it:

1. I tried to unlink pet from person, it worked but showed an error as if it had failed Boxel 2024-05-06 15-59-01 (it also rendered in the wrong order…?)
2. I tried to link the pet again and it said it succeeded but actually failed. The patch code looks correct Boxel 2024-05-06 15-59-48 Boxel 2024-05-06 16-00-14 Boxel 2024-05-06 16-00-28

**Review by lukemelia — APPROVED** [review]

**Comment by tintinthong** [comment]
Screenshot 2024-05-07 at 20 39 53

Is there perhaps something wrong with my prompt here? Im just trying to remove a linked card

**Comment by tintinthong** [comment]
Screenshot 2024-05-07 at 20 48 45

I dont know how to test this well. I changed seller to MagicLinen but it turns out to remove the link. Perhaps my prompt was bad?

**Comment by tintinthong** [comment]
Are these "nested" relationships in scope?

Screenshot 2024-05-07 at 20 46 59

Think its not in scope for this PR. I tried and experience
- it overwrite `unitPrice.amount` which is not the linked field I was targetting
- re-linking will give me something like "Linking unitPrice.currency to "http://localhost:4201/drafts/Currency/2".

**Comment by tintinthong** [comment]
Screenshot 2024-05-07 at 20 48 45

Is this a bad prompt?

**Comment by tintinthong** [comment]
It wud be nice to merge main in for this bcos then ppl can test using both stacks with auto attach which hopefully would work when attaching a card. As opposed to need to manually re-attaching it.

**Comment by tintinthong** [comment]
I tried editing a field. Is the prompt not accurate enough? I think this feature is probably real difficult to test.

Screenshot 2024-05-07 at 21 29 20

**Comment by backspace** [comment]
> I tried editing a field. Is the prompt not accurate enough?
> 
> Screenshot 2024-05-07 at 21 29 20

~~this is maybe similar to what I saw where it says it failed but it actually succeded~~

oh lol no it’s `false` and you asked for `true`

**Comment by burieberry** [comment]
> Are these "nested" relationships in scope?
> 
> Think its not in scope for this PR. I tried and experience
> 
> * it overwrite `unitPrice.amount` which is not the linked field I was targetting
> * re-linking will give me something like "Linking unitPrice.currency to "http://localhost:4201/drafts/Currency/2".

Currently only handling non-nested relationships. Created a ticket for handling the nested: CS-6799.

**Comment by burieberry** [comment]
> I tried editing a field. Is the prompt not accurate enough? I think this feature is probably real difficult to test.
> 
> Screenshot 2024-05-07 at 21 29 20

Ah actually the reason it failed is because you tried to edit the content of the linked card. Right now it fails and tells you to open the card if you want to edit it. I think, ideally, it should tell you to open the card in the stack before offering the patch option. There's this ticket for it but it may still require more discussion about how we want to handle this case: CS-6781

**Comment by burieberry** [comment]
> Screenshot 2024-05-07 at 20 48 45
> 
> Is this a bad prompt?

I think it works now?
change-seller

**Pull request merged**
