### PR TITLE
host: Convert to use scoped CSS

### PR DESCRIPTION
**Pull request by backspace**
This moves styles from `app.css` into `host` components wherever possible. Still remaining in `app.css`:
* classes and variables used in base cards, which cannot yet have scoped CSS
* `.dialog-box` and associated classes, used in two different components, maybe a future extraction
* some global styles like `.link` and `.error`

I updated a few assertions to use `data-test-` selectors as they broke when I shortened class names.

I tried to visually verify each of these changes but I may have missed something as I haven’t been keeping up with all the additions so let me know if you see anything off in areas you’re familiar with 😀

### CODE REVIEW

**Review by jurgenwerk — CHANGES_REQUESTED** [review]
It is very pleasant to see css classes become scoped and less unwieldy 👌

While taking this branch for a spin I spotted regressions:

Before:

image

After - something happened with the border:

image


Card names duplicated:

image

**Review by habdelra — APPROVED** [review]
Love it!

**Comment by burieberry** [comment]
Re: regressions @jurgenwerk caught: Good catch. These might be related to `base` package not having scoped css. If so, maybe we should add scoped css there too?

**Comment by backspace** [comment]
Thanks for finding those, @jurgenwerk, they’re fixed now. The next step is indeed to have scoped CSS for `base`, @burieberry, but it’ll take some doing as it needs to happen via the runtime 🤓

**Review by jurgenwerk — APPROVED** [review]

**Comment by jurgenwerk** [comment]
I'm still seeing double headers (now in main). Not sure if this bag was introduced in this branch but this is the first branch I saw this bug in

image

**Comment by jurgenwerk** [comment]
Maybe another regression from this change? See the odd border on hover

image

**Pull request merged**
