### PR TITLE
Move a few things out of runtime-common that were only consumed by host

### PR DESCRIPTION
**Pull request by lukemelia**
I think @habdelra expected I would find more than this that could be extracted, but I didn't. The main consumption pattern is via the `Realm` class, which is used in both host and realm-server packages.

### CODE REVIEW

**Review by habdelra — COMMENTED** [review]
also make sure to go the other way--move items out of common that are only consumed by the realm-server--like the shims that I mentioned in discord

**Review by burieberry — APPROVED** [review]

**Comment by lukemelia** [comment]
@habdelra shimExternals is used by both host and realm-server currently. I don't see how we can move it unless I am missing something.

**Comment by habdelra** [comment]
Hmmm, it probably shouldn’t be used by host, since we have actual shims for that (as opposed to the no-op ones)

**Review by jurgenwerk — APPROVED** [review]

**Comment by lukemelia** [comment]
I'll create a separate task for shimExternals

**Pull request merged**
