### PR TITLE
Toggle the arrow in the dropdown when selecting a submode

### PR DESCRIPTION
**Pull request by jurgenwerk**
This fixes a bug with the arrow in the submode switcher that gets stuck on selection while it should change its direction.

Before (observe the arrow on the right):

https://github.com/cardstack/boxel/assets/273660/db228ade-2171-4309-bf25-36725bad0510

After:

https://github.com/cardstack/boxel/assets/273660/398a135d-bdb2-43dc-8ee4-36510d3bf837

### CODE REVIEW

**Review by habdelra — APPROVED** [review]

**Comment by habdelra** [comment]
(I just merged upstream to see if that clears the matrix test errors)

**Comment by habdelra** [comment]
I'll look deeper into the failing matrix test in just a moment--the failing test a really simple test that actually doesn't have anything to do with matrix server--it's just some glimmer component state that we are testing

**Comment by jurgenwerk** [comment]
Thanks @habdelra!

**Comment by jurgenwerk** [comment]
I'll merge this since it's unrelated to matrix tests. I suppose that affects all currently opened PRs.

**Pull request merged**
