### PR TITLE
Additional command to copy `.realm.json`  file

### PR DESCRIPTION
**Pull request by FadhlanR**
Without `shopt -s dotglob`, files with a filename starting with a dot won't be copied. In that case, the realm name of cards will always be `Unnamed Workspace` because there is no `.realm.json`.

### CODE REVIEW

**Comment by habdelra** [comment]
`shopt` is a bash command specifically, do we know if that is the shell that is being used in our containers?

**Comment by jurgenwerk** [comment]
This solution and comment suggests this can be fixed using a `.` after the folder name: 

https://superuser.com/questions/61611/how-to-copy-with-cp-to-include-hidden-files-and-hidden-directories-and-their-con#comment1443464_367303

**Comment by FadhlanR** [comment]
@habdelra yes it is shell

**Comment by FadhlanR** [comment]
@jurgenwerk you're right. Updated

**Review by jurgenwerk — APPROVED** [review]

**Pull request merged**
