### PR TITLE
Add navigatable buttons to cards and fields in schema editor

### PR DESCRIPTION
**Pull request by jurgenwerk**
image

The click will lead to opening the card or field's code module in the code editor.

### CODE REVIEW

**Comment by tintinthong** [comment]
https://github.com/cardstack/boxel/assets/8165111/f3ddc12b-b68d-4282-9cb7-525ce001530c

Prob outside of this ticket but I observed that url is shown for linksTo field in pill

**Comment by tintinthong** [comment]
https://github.com/cardstack/boxel/assets/8165111/bf498d3f-e2a1-42a1-94ed-5ce0e5545103

The cursor is active in unclickable places

**Comment by tintinthong** [comment]
Personally, I'd favor a hover highlight (perhaps border) when something is clickable. What do you think? But its fine to deal with styling in another PR if preferred

**Comment by tintinthong** [comment]
Screenshot 2023-10-03 at 3 18 08 PM

Its confusing that the Card and Field show the drafts icon

EDIT: Hmmmm it looks like this is right. this seems to occur when the card & fields defined locally and not have a display name. Now I can see how Card and Field is confusing defaults in this context. The pills should really suggest "Some Card in this file" and "Some Field in this file"

- https://github.com/cardstack/boxel/blob/06564c9952d9b9dc58a356c56285d9ceb0ba4da3/packages/base/card-api.gts#L1767-L1768
- https://github.com/cardstack/boxel/blob/06564c9952d9b9dc58a356c56285d9ceb0ba4da3/packages/base/card-api.gts#L1711

**Comment by jurgenwerk** [comment]
> Prob outside of this ticket but I observed that url is shown for linksTo field in pill

Good catch, I'll take a look

> Personally, I'd favor a hover highlight (perhaps border) when something is clickable

Agree the pill would benefit from some hover/active treatment. Let me come up with something

> Its confusing that the Card and Field show the drafts icon

As you concluded I think we're missing `displayName`s for many definitions. We can add those in another PR

**Comment by jurgenwerk** [comment]
I created a new ticket for fixing field display names. I have also added a slight visual effect when hovering over the pill button so it's clear it's clickable.

**Review by habdelra — APPROVED** [review]

**Pull request merged**
