### PR TITLE
Fix for flaky matrix tests: async DOM signal for playwright

### PR DESCRIPTION
**Pull request by habdelra**
This PR introduces a signal in DOM for playwright when the async has settled in a room card to fix flaky tests where assertions were happening too fast after simulated user interaction. also a little minor cleanup

### CODE REVIEW

**Review by lukemelia — APPROVED** [review]

**Comment by IanCal** [comment]
This test still failed for me, I'm not sure it's to do with checking too soon after - the assertions happen for a good few seconds before they fail. Running the test and stopping on a breakpoint before the last assertion about the room message - the message wasn't updated.

Here I'm logging in the room objective card:
```
  @field usersThatFinishedTask = containsMany(RoomMemberCard, {
    computeVia: function (this: RoomObjectiveCard) {
      console.log("Users that finished task computed field - messages in room are ", this.room.messages);
      let desiredMessages = this.room.messages.filter((m) =>
        m.message.match(/^[\W_b]*[Hh][Ee][Ll][Ll][Oo][\W_\b]*$/),
      );
      return [...new Set(desiredMessages.map((m) => m.author))];
    },
  });
```
and stopping on a breakpoint just after the first hello. This doesn't stop the app, and the objective text doesn't update. You can see here it's only got one message in the room.messages array:
image


If I add a pause, not before the check but before the second message (not between the message and the expect) then all three messages are in the array:
image


If the sleep is after the message being sent it doesn't help:
image

**Comment by habdelra** [comment]
> 

@IanCal Hmmm, that’s interesting, I didn’t see that locally. It looks like the messages in the room that you are logging are correct. Can you also log the final return value for this computed as well? Does the final computed value make sense too, and perhaps it’s an issue with rerendering the template?

**Comment by habdelra** [comment]
And also can you share the test failure message that you see?

**Comment by habdelra** [comment]
Or wait, maybe I’m misunderstanding, are you saying this only works if you intentionally add a pause _before_ the sendMessage()? (Maybe I need to wait for settling in another place I’m not currently waiting)

**Comment by IanCal** [comment]
> Or wait, maybe I’m misunderstanding, are you saying this only works if you intentionally add a pause _before_ the sendMessage()? (Maybe I need to wait for settling in another place I’m not currently waiting)

Yep, rather than between the sendMessage and the expect in the test. It seems like it's to do with the messages being sent together quickly and that causing an issue elsewhere.

>  It looks like the messages in the room that you are logging are correct. Can you also log the final return value for this computed as well? Does the final computed value make sense too, and perhaps it’s an issue with rerendering the template?

The messages in the room look fine, and you can see new messages appearing in logging in room.gts. However the room-objective computed doesn't see all the messages. Here's the final logs without the sleep:

image

room.gts shows the new messages are seen (which makes sense given that they're rendered), but logging in room objective the last time the computed function is run it returns no users - and that's because when it runs this.room.messages is missing the last *two* events. I'm logging there the list of users (empty) and this.room.messages, which has just one element. 

It's not run out of sequence, as in it's not run with the correct 3 messages, then later run with just one which overrides the output. 

I feel like this means there must be wither 


The final error message for the test is : 

```
Error: Timed out 5000ms waiting for expect(received).toContainText(expected)

- Expected string  - 1
+ Received string  + 7

- Completed 1 of 2 (50%)
+
+           Completed
+           0
+           of
+           2
+           (0%)
+         
Call log:
  - expect.toContainText with timeout 5000ms
  - waiting for locator('[data-test-objective-progress]')
  -   locator resolved to <strong data-test-objective-progress="">…</strong>
  -   unexpected value "
          Completed
          0
          of
          2
          (0%)
        "
  -   locator resolved to <strong data-test-objective-progress="">…</strong>
  -   unexpected value "
          Completed
          0
          of
          2
          (0%)
        "
  -   locator resolved to <strong data-test-objective-progress="">…</strong>
  -   unexpected value "
          Completed
          0
          of
          2
          (0%)
        "
  -   locator resolved to <strong data-test-objective-progress="">…</strong>
  -   unexpected value "
          Completed
          0
          of
          2
          (0%)
        "
  -   locator resolved to <strong data-test-objective-progress="">…</strong>
  -   unexpected value "
          Completed
          0
          of
          2
          (0%)
        "
  -   locator resolved to <strong data-test-objective-progress="">…</strong>
  -   unexpected value "
          Completed
          0
          of
          2
          (0%)
        "
  -   locator resolved to <strong data-test-objective-progress="">…</strong>
  -   unexpected value "
          Completed
          0
          of
          2
          (0%)
        "
  -   locator resolved to <strong data-test-objective-progress="">…</strong>
  -   unexpected value "
          Completed
          0
          of
          2
          (0%)
        "
  -   locator resolved to <strong data-test-objective-progress="">…</strong>
  -   unexpected value "
          Completed
          0
          of
          2
          (0%)
        "


  53 |     await sendMessage(page, `_Hello_`);
  54 |     console.log("After message, before expect");
> 55 |     await expect(page.locator(`[data-test-objective-progress]`)).toContainText(
     |                                                                  ^
  56 |       `Completed 1 of 2 (50%)`,
  57 |     );
  58 |     await expect(page.locator(`[data-test-objective-remaining]`)).toContainText(

    at /home/ian/projects/boxel/packages/matrix/tests/objectives.spec.ts:55:66
```

Which does match what's in the UI, the message doesn't update.

If I break before the expect and write a message manually, it updates with the full list of messages.

**Comment by IanCal** [comment]
In room.gts, messages is an async computed and the new messages come in *while* it's being executed, and it's not run again. The end of the function tries to get the updated cache in case two things are run at once but that doesn't handle this case (where it's not run at all)

A bit hacky but I tried adding a loop at the end to essentially do this:

```
while this.events.length > totalEventsAtStart:
    updateCache
```

This kinda solves the immediate issue, but it really just shrinks the window of time where updated events can be missed and leaves a more general issue IMO with recomputes. The behaviour we probably want is described by keepLatest in ember concurrency (allow the current one to finish, then rerun with the most recent invocation and drop any stale non-started ones).

**Comment by habdelra** [comment]
ahhh, good sluething--i understand the issue now. yeah this is a tricky one. another thought is that we return serialized message card data instead of actual card instance--if we did that this would be synchronous. we could then deserialize them on the outside in the room component using a resource. it does mean that any computeds based on the messages now have to reason in serialized data instead of actual card instances which is kind of sad since you won't have types to enforce things... maybe we could add our own specific serialized message data type  (i like the types mostly from a refactor standpoint so that if we decide we want to change the shape of a message the types show us what all needs to change).


EDIT: or actually it's just the attached cards that need deserialization (and hence async). let's just deserialize those on the outside.

**Comment by habdelra** [comment]
@IanCal wanna try this again on your system? the messages computed is now synchronous so hopefully your issues have been resolved.

**Review by IanCal — APPROVED** [review]

**Comment by IanCal** [comment]
@habdelra this fixes the test for me thanks - it may be a pattern we need to promote elsewhere. I had a dig through the flow for field re-computation and I feel like we could solve this at a higher level (checking before and after if any fields were updated) but my first attempts haven't worked, but that's a bigger discussion.

**Comment by habdelra** [comment]
> @habdelra this fixes the test for me thanks - it may be a pattern we need to promote elsewhere. I had a dig through the flow for field re-computation and I feel like we could solve this at a higher level (checking before and after if any fields were updated) but my first attempts haven't worked, but that's a bigger discussion.

Checking what exactly? Computeds are super free form. They maybe include interior fields of its own card, or other cards, or no interior fields of any cards (maybe it’s just running a fetch on some external system). If it’s own fields have changed while it’s running async, the idea is that the card will be invalidated by glimmer and the the computed will be reexecuted again (there is a async process to recompute as part of the property descriptor’s set.). Perhaps the issue is around the consumption of the computed. Perhaps what we were seeing was a big in the consumption of the computed that prevented the invalidation from happening the subsequent time. (Were the bug was that we are missing the consumption somewhere such that the Room.messages was not be recomputed). The way we are rendering Room.messages is actually a little weird and I could see that there might be a consumption problem—instead of rendering the Room card directly, we are actually pulling apart it’s messages field and rending each one on its own. We do this mostly because we don’t really have a good story around a card that can persist mutations to its state (eg the send message button). So we pull it apart actually when we render it. That might be the actual bug….

**Pull request merged**
