### PR TITLE
Snowboard lesson planner champagne drinking

### PR DESCRIPTION
**Pull request by habdelra**
This is a lesson planner for snowboard carving

image

### CODE REVIEW

**Review by tintinthong — APPROVED** [review]
Interesting. I think something is not working as expected with the SSE. When I edit bodyPosition degrees, the edit mode doesn't seem to triggger a save. Its as tho the save within code mode doesn't react 

But, when I edit Diagram Type, the save works. Perhaps worth filing a ticket

This certainly opens up my eyes to the technicalities in the angles of snowboarding hahah. Looks like u skate regular!

**Comment by habdelra** [comment]
> Interesting. I think something is not working as expected with the SSE. When I edit bodyPosition degrees, the edit mode doesn't seem to triggger a save. Its as tho the save within code mode doesn't react
> 
> But, when I edit Diagram Type, the save works. Perhaps worth filing a ticket
> 
> This certainly opens up my eyes to the technicalities in the angles of snowboarding hahah. Looks like u skate regular!

yeah i was seeing a similar thing as well. in this case its editing an item in a containsMany field. I think specifically that is not triggering a save. I'll file ticket around that.

I think i'm also gonna add an "edge angle" field as well, which is probably another important consideration to capture in this diagram

**Comment by habdelra** [comment]
Filed CS-6862 around the autosave not working for fields within a composite containsMany

**Comment by habdelra** [comment]
I thought about making a diagram for goofy too, but i'm time-boxing this :laughing:

**Pull request merged**
