### PR TITLE
Fix accordion height bug

### PR DESCRIPTION
**Pull request by FadhlanR**
Ticket: CS-6104

Before:
Screenshot 2023-10-16 at 17 02 15

After:

https://github.com/cardstack/boxel/assets/12637010/def21d0f-435b-4211-9346-f8d360446c3e

### CODE REVIEW

**Review by jurgenwerk — APPROVED** [review]

**Review by lukemelia — APPROVED** [review]

**Comment by jurgenwerk** [comment]
@FadhlanR hold on, I don't think this solves the problem. I tested this by manually adding your change and you can still see the visual bug:

image

**Comment by FadhlanR** [comment]
> @FadhlanR hold on, I don't think this solves the problem. I tested this by manually adding your change and you can still see the visual bug:
> 
> 
> 
> image
> 
> 

@jurgenwerk have you removed 'height' in 'card-adoption-chain' class?

**Comment by burieberry** [comment]
> > @FadhlanR hold on, I don't think this solves the problem. I tested this by manually adding your change and you can still see the visual bug:
> 
> @jurgenwerk have you removed 'height' in 'card-adoption-chain' class?

Here's what worked:
- removed `overflow-y: auto` from `.content` in Accordion ui component (https://github.com/cardstack/boxel/blob/a56e58f30df62d9de17cf3780ca80b352dfbb85d/packages/boxel-ui/addon/src/components/accordion/item/index.gts#L58)
- added it instead to `.card-adoption-chain` class. I think you will need to subtract the header's height from the 100% height so that the bottom doesn't get cropped. Or add extra bottom padding.

We were trying to provide the end user scrolling ability for their content. However, this doesn't work when the user has another outer `div` for their content. Either we don't provide the scroll and leave it up to the user, or the user can use a class name arg that goes with the accordion component. Something like: `class="content @contentClass"`. Since it seems difficult to enforce this, we can remove it from the accordion component.

**Comment by FadhlanR** [comment]
> > > @FadhlanR hold on, I don't think this solves the problem. I tested this by manually adding your change and you can still see the visual bug:
> > 
> > 
> > @jurgenwerk have you removed 'height' in 'card-adoption-chain' class?
> 
> Here's what worked:
> 
> * removed `overflow-y: auto` from `.content` in Accordion ui component (https://github.com/cardstack/boxel/blob/a56e58f30df62d9de17cf3780ca80b352dfbb85d/packages/boxel-ui/addon/src/components/accordion/item/index.gts#L58
>   )
> * added it instead to `.card-adoption-chain` class. I think you will need to subtract the header's height from the 100% height so that the bottom doesn't get cropped. Or add extra bottom padding.
> 
> We were trying to provide the end user scrolling ability for their content. However, this doesn't work when the user has another outer `div` for their content. Either we don't provide the scroll and leave it up to the user, or the user can use a class name arg that goes with the accordion component. Something like: `class="content @contentClass"`. Since it seems difficult to enforce this, we can remove it from the accordion component.

I've added `contentClass` arguments to the accordion item since it seems easier for the user.


https://github.com/cardstack/boxel/assets/12637010/1003e316-96ba-48e7-a86a-e3591bd172a3

**Pull request merged**
